import type { CourseItem, LessonItem } from "./dashboard.types";

type LearningErrorKind = "unauthenticated" | "forbidden" | "parent-not-found" | "invalid-request" | "recoverable";
export class LearningRequestError extends Error { constructor(readonly kind: LearningErrorKind, message: string) { super(message); this.name = "LearningRequestError"; } }

const coursesPath = "/api/v1/learning/courses/?page=1&page_size=20";
const lessonsPath = (courseId: string) => `/api/v1/learning/courses/${encodeURIComponent(courseId)}/lessons/?page=1&page_size=20`;

function record(value: unknown): Record<string, unknown> | null { return typeof value === "object" && value !== null ? value as Record<string, unknown> : null; }
function stringValue(value: unknown): value is string { return typeof value === "string" && value.length > 0; }
function course(value: unknown): CourseItem | null { const r = record(value); return r && stringValue(r.id) && stringValue(r.code) && stringValue(r.title) && r.state === "published" ? { id: r.id, code: r.code, title: r.title, state: "published" } : null; }
function lesson(value: unknown): LessonItem | null { const r = record(value); return r && stringValue(r.id) && stringValue(r.code) && stringValue(r.title) && typeof r.position === "number" && Number.isInteger(r.position) && r.position > 0 && r.state === "published" ? { id: r.id, code: r.code, title: r.title, position: r.position, state: "published" } : null; }
function statusError(status: number): LearningRequestError { if (status === 401) return new LearningRequestError("unauthenticated", "session required"); if (status === 403) return new LearningRequestError("forbidden", "access denied"); if (status === 404) return new LearningRequestError("parent-not-found", "parent not found"); if (status === 400) return new LearningRequestError("invalid-request", "invalid request"); return new LearningRequestError("recoverable", `learning request failed: ${status}`); }
async function readResults(response: Response, parse: (value: unknown) => CourseItem | LessonItem | null, signal?: AbortSignal): Promise<readonly (CourseItem | LessonItem)[]> { if (!response.ok) throw statusError(response.status); const payload: unknown = await response.json(); const root = record(payload); if (!root || !Array.isArray(root.results)) throw new LearningRequestError("recoverable", "malformed learning envelope"); const output = root.results.map(parse); if (output.some((value) => value === null)) throw new LearningRequestError("recoverable", "malformed learning item"); if (signal?.aborted) throw new DOMException("aborted", "AbortError"); return output as readonly (CourseItem | LessonItem)[]; }
async function get(path: string, parse: (value: unknown) => CourseItem | LessonItem | null, signal?: AbortSignal) { try { return await readResults(await fetch(path, { credentials: "same-origin", headers: { Accept: "application/json" }, signal }), parse, signal); } catch (error) { if (error instanceof LearningRequestError || (error instanceof DOMException && error.name === "AbortError")) throw error; throw new LearningRequestError("recoverable", "learning request unavailable"); } }
export async function fetchCourses(options: { readonly signal?: AbortSignal } = {}): Promise<readonly CourseItem[]> { return await get(coursesPath, course, options.signal) as readonly CourseItem[]; }
export async function fetchLessons(courseId: string, options: { readonly signal?: AbortSignal } = {}): Promise<readonly LessonItem[]> { if (!stringValue(courseId)) throw new LearningRequestError("invalid-request", "course id required"); return await get(lessonsPath(courseId), lesson, options.signal) as readonly LessonItem[]; }
