# Generated by Django 5.2.17 on 2026-09-07 07:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_primary_key_immutability'),
        ('platform_tenant', '0003_synthetic_membership_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('state', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('content', models.TextField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(default='')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='learning.lesson')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mentor_id', models.UUIDField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='platform_tenant.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='learning.learningpath'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='learning.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='platform_tenant.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='learning.module'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_lesson_tenant_id_uniq'),
        ),
        migrations.AddField(
            model_name='progress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='progress',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='learning.submission'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant', 'lesson', 'state'], name='learn_asgn_tenant_les_ix'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'lesson', 'code'), name='learning_assign_tenant_lesson_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_assign_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'published', 'closed'])), name='learning_assign_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='learning_assign_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='learning_assign_title_nonempty'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['tenant', 'state'], name='learn_path_tenant_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='learning_path_tenant_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_path_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'published', 'archived'])), name='learning_path_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='learning_path_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='learning_path_title_nonempty'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['tenant', 'course', 'state'], name='learn_mod_tenant_course_ix'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'code'), name='learning_module_tenant_course_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'position'), name='learning_module_tenant_course_pos_uniq'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_module_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='learning_module_pos_positive'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'published', 'archived'])), name='learning_module_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='learning_module_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='learning_module_title_nonempty'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['tenant', 'lesson', 'state'], name='learn_prog_tenant_les_ix'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['tenant', 'student_id', 'state'], name='learn_prog_tenant_stud_ix'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('tenant', 'lesson', 'student_id'), name='learning_prog_tenant_lesson_student_uniq'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_prog_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['not_started', 'in_progress', 'completed'])), name='learning_prog_state_valid'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant', 'assignment', 'state'], name='learn_subm_tenant_asgn_ix'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant', 'student_id', 'state'], name='learn_subm_tenant_stud_ix'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('tenant', 'assignment', 'student_id'), name='learning_subm_tenant_assign_student_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_submission_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'submitted', 'under_review', 'reviewed'])), name='learning_subm_state_valid'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tenant', 'submission'], name='learn_feed_tenant_subm_ix'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_feedback_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='learning_feedback_content_nonempty'),
        ),
    ]
