# Generated by Django 5.2.17 on 2026-09-07 12:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_phase2_learning_rls'),
        ('platform_tenant', '0003_synthetic_membership_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticMediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('storage_key', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('quarantined', 'Quarantined')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='learning.lesson')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_media_attachments', to='platform_tenant.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'lesson', 'state'], name='learn_media_tenant_les_ix')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='learning_synthetic_media_tenant_id_uniq'), models.UniqueConstraint(fields=('tenant', 'storage_key'), name='learning_synthetic_media_tenant_storage_uniq'), models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'processing', 'ready', 'quarantined'])), name='learning_synthetic_media_state_valid'), models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='learning_synthetic_media_title_nonempty'), models.CheckConstraint(condition=models.Q(('storage_key', ''), _negated=True), name='learning_synthetic_media_storage_key_nonempty')],
            },
        ),
    ]
