# Generated by Django 5.2.17 on 2026-09-07 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_syntheticmediaattachment_rls'),
        ('platform_tenant', '0003_synthetic_membership_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmissionMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_count', models.PositiveIntegerField(default=0)),
                ('under_review_count', models.PositiveIntegerField(default=0)),
                ('reviewed_count', models.PositiveIntegerField(default=0)),
                ('last_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_metrics', to='learning.assignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_metrics', to='platform_tenant.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'assignment'], name='asm_tenant_assignment_ix')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='learning_asm_tenant_id_uniq'), models.UniqueConstraint(fields=('tenant', 'assignment'), name='learning_asm_tenant_assignment_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CourseProgressAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('last_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_aggregates', to='learning.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress_aggregates', to='platform_tenant.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'student_id'], name='cpa_tenant_student_ix')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='learning_cpa_tenant_id_uniq'), models.UniqueConstraint(fields=('tenant', 'student_id', 'course'), name='learning_cpa_tenant_student_course_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RoleActivityFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_event_id', models.UUIDField(db_index=True)),
                ('target_role', models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('parent', 'Parent'), ('admin', 'Admin')], max_length=16)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('activity_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_activity_feeds', to='platform_tenant.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'target_role', 'user_id'], name='raf_tenant_role_user_ix'), models.Index(fields=['tenant', '-occurred_at'], name='raf_tenant_occurred_ix')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='learning_raf_tenant_id_uniq'), models.UniqueConstraint(fields=('tenant', 'source_event_id', 'target_role'), name='learning_raf_tenant_source_event_role_uniq')],
            },
        ),
    ]
