# Generated by Django 5.2.17 on 2026-09-07 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_p3_vs2_projections_rls'),
        ('platform_tenant', '0003_synthetic_membership_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionDeadLetterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('raw_payload_zero_pii', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectionWatermark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projection_name', models.CharField(max_length=64)),
                ('last_event_id', models.UUIDField()),
                ('last_occurred_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='roleactivityfeed',
            name='raf_tenant_occurred_ix',
        ),
        migrations.AddIndex(
            model_name='roleactivityfeed',
            index=models.Index(fields=['tenant', '-occurred_at', '-id'], name='raf_tenant_cursor_ix'),
        ),
        migrations.AddField(
            model_name='projectiondeadletterevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_dead_letters', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='projectionwatermark',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_watermarks', to='platform_tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='projectiondeadletterevent',
            index=models.Index(fields=['tenant', 'event_type'], name='dle_tenant_type_ix'),
        ),
        migrations.AddConstraint(
            model_name='projectiondeadletterevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_dle_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectiondeadletterevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_id'), name='learning_dle_tenant_event_uniq'),
        ),
        migrations.AddIndex(
            model_name='projectionwatermark',
            index=models.Index(fields=['tenant', 'projection_name'], name='pw_tenant_proj_ix'),
        ),
        migrations.AddConstraint(
            model_name='projectionwatermark',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_pw_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='projectionwatermark',
            constraint=models.UniqueConstraint(fields=('tenant', 'projection_name'), name='learning_pw_tenant_projection_uniq'),
        ),
    ]
