# Generated by Django 5.2.17 on 2026-09-08 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_p3_vs2_watermark_dlq_rls'),
        ('platform_tenant', '0003_synthetic_membership_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(db_index=True, max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=500)),
                ('notification_type', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('dispatching', 'Dispatching'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_items', to='platform_tenant.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'user_id', '-created_at'], name='notif_tenant_user_created_ix'), models.Index(fields=['tenant', 'role', 'state'], name='notif_tenant_role_state_ix')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='learning_notification_tenant_id_uniq'), models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='learning_notification_tenant_idemp_uniq')],
            },
        ),
    ]
