# Generated by Django 5.2.17 on 2026-09-08 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_p3_vs4_gamification_rls'),
        ('platform_tenant', '0003_synthetic_membership_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_cohort_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('max_capacity', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='learning.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed')], default='enrolled', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='learning.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='learning.course')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='learning.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisites', to='platform_tenant.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['tenant', 'course', 'is_active'], name='cohort_tenant_course_act_ix'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'code'), name='learning_cohort_tenant_course_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'id'), name='learning_cohort_tenant_course_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_cohort_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='learning_cohort_code_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='learning_cohort_title_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('max_capacity__gt', 0)), name='learning_cohort_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['tenant', 'student_id', 'status'], name='enroll_tenant_student_st_ix'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['tenant', 'cohort', 'status'], name='enroll_tenant_cohort_st_ix'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['tenant', 'course', 'status'], name='enroll_tenant_course_st_ix'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_enrollment_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('tenant', 'student_id', 'course'), name='learning_enrollment_tenant_student_course_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='learning_enrollment_tenant_idemp_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['enrolled', 'active', 'suspended', 'completed'])), name='learning_enrollment_status_valid'),
        ),
        migrations.AddIndex(
            model_name='courseprerequisite',
            index=models.Index(fields=['tenant', 'course'], name='prereq_tenant_course_ix'),
        ),
        migrations.AddIndex(
            model_name='courseprerequisite',
            index=models.Index(fields=['tenant', 'prerequisite_course'], name='prereq_tenant_reqfor_ix'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_prereq_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'prerequisite_course'), name='learning_prereq_tenant_course_prereq_uniq'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('course', models.F('prerequisite_course')), _negated=True), name='learning_prereq_no_self_reference'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: schema_editor.execute(
                """
                ALTER TABLE learning_courseenrollment
                ADD CONSTRAINT fk_enrollment_cohort_course_tenant
                FOREIGN KEY (tenant_id, course_id, cohort_id)
                REFERENCES learning_cohort (tenant_id, course_id, id)
                ON DELETE SET NULL;
                """
            ) if schema_editor.connection.vendor == "postgresql" else None,
            reverse_code=lambda apps, schema_editor: schema_editor.execute(
                """
                ALTER TABLE learning_courseenrollment
                DROP CONSTRAINT IF EXISTS fk_enrollment_cohort_course_tenant;
                """
            ) if schema_editor.connection.vendor == "postgresql" else None,
        ),
    ]
