# Generated by Django 5.2.17 on 2026-09-09 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_p3_vs12_learning_portfolio_rls'),
        ('platform_tenant', '0004_p3_vs12_guardian_access_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_by', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_calculation_runs', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('metric_key', models.CharField(choices=[('CODING_VELOCITY', 'Coding Velocity'), ('CONCEPT_MASTERY', 'Concept Mastery'), ('PROBLEM_SOLVING', 'Problem Solving'), ('PERSISTENCE', 'Persistence'), ('CODE_QUALITY', 'Code Quality')], max_length=64)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('growth_delta', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('snapshot_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='metric_snapshots', to='learning.calculationrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_metric_snapshots', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='InsightGenerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=64)),
                ('event_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PROCESSED', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('triggered_by', models.UUIDField(db_index=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='generation_events', to='learning.calculationrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_generation_events', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LearningInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('insight_type', models.CharField(choices=[('COMPETENCY_GROWTH', 'Competency Growth'), ('STRENGTH_AREA', 'Strength Area'), ('MOMENTUM_STREAK', 'Momentum Streak'), ('FOCUS_RECOMMENDATION', 'Focus Recommendation'), ('MASTERY_MILESTONE', 'Mastery Milestone')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=16)),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('RETRACTED', 'Retracted')], default='ACTIVE', max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('retracted_at', models.DateTimeField(blank=True, null=True)),
                ('retraction_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='learning_insights', to='learning.calculationrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_insights', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LearningMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('milestone_code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACHIEVED', 'Achieved'), ('RETRACTED', 'Retracted')], default='ACHIEVED', max_length=20)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('retracted_at', models.DateTimeField(blank=True, null=True)),
                ('retraction_reason', models.TextField(blank=True, null=True)),
                ('evidence_digest', models.CharField(max_length=64)),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learning_milestones', to='learning.coursecertificate')),
                ('source_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='learning_milestones', to='learning.submission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_milestones', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrowthTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('competency_domain', models.CharField(max_length=64)),
                ('trend_direction', models.CharField(choices=[('ACCELERATING', 'Accelerating'), ('STEADY', 'Steady'), ('DEVELOPING', 'Developing'), ('NEEDS_SUPPORT', 'Needs Support')], default='DEVELOPING', max_length=32)),
                ('current_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('velocity_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_milestones_achieved', models.IntegerField(default=0)),
                ('competency_vectors', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='growth_trends', to='learning.calculationrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_growth_trends', to='platform_tenant.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['tenant', 'started_at'], name='idx_calcrun_tenant_started'),
        ),
        migrations.AddIndex(
            model_name='calculationrun',
            index=models.Index(fields=['tenant', 'triggered_by'], name='idx_calcrun_tenant_trigger'),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_calcrun_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['RUNNING', 'COMPLETED', 'FAILED'])), name='learning_calcrun_status_check'),
        ),
        migrations.AddConstraint(
            model_name='calculationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['COMPLETED', 'FAILED']), ('completed_at__isnull', False)), models.Q(('status', 'RUNNING'), ('completed_at__isnull', True)), _connector='OR'), name='learning_calcrun_completion_check'),
        ),
        migrations.AddIndex(
            model_name='growthmetricsnapshot',
            index=models.Index(fields=['tenant', 'student_id', 'metric_key', 'snapshot_date'], name='idx_growth_metric_timeline'),
        ),
        migrations.AddConstraint(
            model_name='growthmetricsnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_metric_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='growthmetricsnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'student_id', 'metric_key', 'snapshot_date'), name='learning_metric_daily_student_uniq'),
        ),
        migrations.AddConstraint(
            model_name='growthmetricsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('metric_key__in', ['CODING_VELOCITY', 'CONCEPT_MASTERY', 'PROBLEM_SOLVING', 'PERSISTENCE', 'CODE_QUALITY'])), name='learning_metric_key_check'),
        ),
        migrations.AddConstraint(
            model_name='growthmetricsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('metric_value__gte', 0.0), ('metric_value__lte', 1000.0)), name='learning_metric_value_range'),
        ),
        migrations.AddConstraint(
            model_name='growthmetricsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('baseline_value__isnull', True), models.Q(('baseline_value__gte', 0.0), ('baseline_value__lte', 1000.0)), _connector='OR'), name='learning_metric_baseline_range'),
        ),
        migrations.AddIndex(
            model_name='insightgenerationevent',
            index=models.Index(fields=['tenant', 'student_id', 'calculation_run'], name='idx_genevent_audit'),
        ),
        migrations.AddConstraint(
            model_name='insightgenerationevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_genevent_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='insightgenerationevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'student_id', 'event_type', 'event_key'), name='learning_genevent_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='insightgenerationevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PROCESSED', 'REJECTED', 'FAILED'])), name='learning_genevent_status_check'),
        ),
        migrations.AddConstraint(
            model_name='insightgenerationevent',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0), ('retry_count__lte', 10)), name='learning_genevent_retry_check'),
        ),
        migrations.AddConstraint(
            model_name='insightgenerationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['REJECTED', 'FAILED']), ('failure_reason__isnull', False)), models.Q(('status', 'PROCESSED'), ('failure_reason__isnull', True)), _connector='OR'), name='learning_genevent_failure_check'),
        ),
        migrations.AddIndex(
            model_name='learninginsight',
            index=models.Index(fields=['tenant', 'student_id', 'created_at'], name='idx_insight_active_feed'),
        ),
        migrations.AddConstraint(
            model_name='learninginsight',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_insight_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='learninginsight',
            constraint=models.UniqueConstraint(condition=models.Q(('lifecycle_status', 'ACTIVE')), fields=('tenant', 'student_id', 'insight_type'), name='uq_insight_singleton_active'),
        ),
        migrations.AddConstraint(
            model_name='learninginsight',
            constraint=models.CheckConstraint(condition=models.Q(('insight_type__in', ['COMPETENCY_GROWTH', 'STRENGTH_AREA', 'MOMENTUM_STREAK', 'FOCUS_RECOMMENDATION', 'MASTERY_MILESTONE'])), name='learning_insight_type_check'),
        ),
        migrations.AddConstraint(
            model_name='learninginsight',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_level__in', ['HIGH', 'MEDIUM', 'LOW'])), name='learning_insight_confidence_check'),
        ),
        migrations.AddConstraint(
            model_name='learninginsight',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status__in', ['ACTIVE', 'SUPERSEDED', 'RETRACTED'])), name='learning_insight_lifecycle_check'),
        ),
        migrations.AddConstraint(
            model_name='learninginsight',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lifecycle_status', 'RETRACTED'), ('retracted_at__isnull', False), ('retraction_reason__isnull', False)), models.Q(('lifecycle_status__in', ['ACTIVE', 'SUPERSEDED']), ('retracted_at__isnull', True), ('retraction_reason__isnull', True)), _connector='OR'), name='learning_insight_retraction_check'),
        ),
        migrations.AddIndex(
            model_name='learningmilestone',
            index=models.Index(fields=['tenant', 'student_id', 'achieved_at'], name='idx_milestone_chronological'),
        ),
        migrations.AddConstraint(
            model_name='learningmilestone',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_milestone_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='learningmilestone',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACHIEVED')), fields=('tenant', 'student_id', 'milestone_code'), name='uq_milestone_active_code'),
        ),
        migrations.AddConstraint(
            model_name='learningmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACHIEVED', 'RETRACTED'])), name='learning_milestone_status_check'),
        ),
        migrations.AddConstraint(
            model_name='learningmilestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RETRACTED'), ('retracted_at__isnull', False), ('retraction_reason__isnull', False)), models.Q(('status', 'ACHIEVED'), ('retracted_at__isnull', True), ('retraction_reason__isnull', True)), _connector='OR'), name='learning_milestone_retraction_check'),
        ),
        migrations.AddConstraint(
            model_name='studentgrowthtrend',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='learning_trend_tenant_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentgrowthtrend',
            constraint=models.UniqueConstraint(fields=('tenant', 'student_id', 'competency_domain'), name='learning_trend_domain_uniq'),
        ),
        migrations.AddConstraint(
            model_name='studentgrowthtrend',
            constraint=models.CheckConstraint(condition=models.Q(('trend_direction__in', ['ACCELERATING', 'STEADY', 'DEVELOPING', 'NEEDS_SUPPORT'])), name='learning_trend_direction_check'),
        ),
        migrations.AddConstraint(
            model_name='studentgrowthtrend',
            constraint=models.CheckConstraint(condition=models.Q(('current_score__gte', 0.0), ('current_score__lte', 100.0)), name='learning_trend_score_range'),
        ),
        migrations.AddConstraint(
            model_name='studentgrowthtrend',
            constraint=models.CheckConstraint(condition=models.Q(('velocity_rate__gte', -100.0), ('velocity_rate__lte', 100.0)), name='learning_trend_velocity_range'),
        ),
        migrations.AddConstraint(
            model_name='studentgrowthtrend',
            constraint=models.CheckConstraint(condition=models.Q(('total_milestones_achieved__gte', 0)), name='learning_trend_milestones_non_negative'),
        ),
    ]
