# Generated by Django 5.2.17 on 2026-09-09 22:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_phase3_vs14_learning_operations_rls'),
        ('platform_tenant', '0004_p3_vs12_guardian_access_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStudentSuccessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('target_period', models.CharField(choices=[('CURRENT_TERM', 'Current Term'), ('ACADEMIC_YEAR', 'Academic Year'), ('SUMMER_INTENSIVE', 'Summer Intensive'), ('MONTHLY_SPRINT', 'Monthly Sprint'), ('QUARTERLY_CYCLE', 'Quarterly Cycle'), ('LONG_TERM_FOUNDATION', 'Long Term Foundation')], max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_studentsuccessplan',
            },
        ),
        migrations.CreateModel(
            name='SuccessActionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('sequence_order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_authoritative', models.BooleanField(default=False)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_successactionstep',
            },
        ),
        migrations.CreateModel(
            name='SuccessAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('CREATE_SUCCESS_PLAN', 'Create Success Plan'), ('PAUSE_SUCCESS_PLAN', 'Pause Success Plan'), ('RESUME_SUCCESS_PLAN', 'Resume Success Plan'), ('COMPLETE_SUCCESS_PLAN', 'Complete Success Plan'), ('SUPERSEDE_SUCCESS_PLAN', 'Supersede Success Plan'), ('ARCHIVE_SUCCESS_PLAN', 'Archive Success Plan'), ('CREATE_ACTION_STEP', 'Create Action Step'), ('UPDATE_ACTION_STEP', 'Update Action Step'), ('TRANSITION_ACTION_STEP', 'Transition Action Step'), ('APPEND_TIMELINE_EVENT', 'Append Timeline Event')], max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_successauditlog',
            },
        ),
        migrations.CreateModel(
            name='SuccessTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('GOAL_ANCHORED', 'Goal Anchored'), ('INSIGHT_CONNECTED', 'Insight Connected'), ('REFLECTION_TIED', 'Reflection Tied'), ('ACTION_DISPATCHED', 'Action Dispatched'), ('MILESTONE_PROGRESSION', 'Milestone Progression'), ('TIMELINE_EVENT_AMENDED', 'Timeline Event Amended')], max_length=64)),
                ('headline', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, null=True)),
                ('client_mutation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_successtimelineevent',
            },
        ),
        migrations.RemoveConstraint(
            model_name='goalactionplan',
            name='chk_action_completed_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='studentlearninggoal',
            name='chk_goal_completion_consistency',
        ),
        migrations.AddConstraint(
            model_name='goalactionplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), ('completed_at__isnull', False)), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='chk_action_completed_consistency'),
        ),
        migrations.AddConstraint(
            model_name='studentlearninggoal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACHIEVED'), ('completed_at__isnull', False)), models.Q(models.Q(('status', 'ACHIEVED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='chk_goal_completion_consistency'),
        ),
        migrations.AddField(
            model_name='learningstudentsuccessplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_success_plans', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='successactionstep',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_steps', to='learning.learningstudentsuccessplan'),
        ),
        migrations.AddField(
            model_name='successactionstep',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_action_steps', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='successauditlog',
            name='target_action_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='learning.successactionstep'),
        ),
        migrations.AddField(
            model_name='successauditlog',
            name='target_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='learning.learningstudentsuccessplan'),
        ),
        migrations.AddField(
            model_name='successauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_audit_logs', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_events', to='learning.learningstudentsuccessplan'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='replaces_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='amendments', to='learning.successtimelineevent'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='target_action_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_events', to='learning.successactionstep'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='target_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_events', to='learning.studentlearninggoal'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='target_insight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_events', to='learning.learninginsight'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='target_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_events', to='learning.learningmilestone'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='target_reflection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='timeline_events', to='learning.learningreflection'),
        ),
        migrations.AddField(
            model_name='successtimelineevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_timeline_events', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='successauditlog',
            name='target_timeline_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='learning.successtimelineevent'),
        ),
        migrations.AddIndex(
            model_name='learningstudentsuccessplan',
            index=models.Index(fields=['tenant', 'student_id', '-created_at'], name='idx_successplan_tenant_student'),
        ),
        migrations.AddConstraint(
            model_name='learningstudentsuccessplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_studentsuccessplan_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='learningstudentsuccessplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tenant', 'student_id'), name='uq_successplan_student_active'),
        ),
        migrations.AddConstraint(
            model_name='learningstudentsuccessplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'PAUSED', 'COMPLETED', 'SUPERSEDED', 'ARCHIVED'])), name='chk_successplan_status'),
        ),
        migrations.AddConstraint(
            model_name='learningstudentsuccessplan',
            constraint=models.CheckConstraint(condition=models.Q(('target_period__in', ['CURRENT_TERM', 'ACADEMIC_YEAR', 'SUMMER_INTENSIVE', 'MONTHLY_SPRINT', 'QUARTERLY_CYCLE', 'LONG_TERM_FOUNDATION'])), name='chk_successplan_target_period'),
        ),
        migrations.AddConstraint(
            model_name='learningstudentsuccessplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), ('completed_at__isnull', True), ('paused_at__isnull', True), ('superseded_at__isnull', True), ('archived_at__isnull', True)), models.Q(('status', 'PAUSED'), ('paused_at__isnull', False), ('completed_at__isnull', True), ('superseded_at__isnull', True), ('archived_at__isnull', True)), models.Q(('status', 'COMPLETED'), ('completed_at__isnull', False), ('paused_at__isnull', True), ('superseded_at__isnull', True), ('archived_at__isnull', True)), models.Q(('status', 'SUPERSEDED'), ('superseded_at__isnull', False), ('archived_at__isnull', True)), models.Q(('status', 'ARCHIVED'), ('archived_at__isnull', False)), _connector='OR'), name='chk_successplan_status_consistency'),
        ),
        migrations.AddIndex(
            model_name='successactionstep',
            index=models.Index(fields=['tenant', 'plan', 'sequence_order'], name='idx_actionstep_tenant_plan_seq'),
        ),
        migrations.AddConstraint(
            model_name='successactionstep',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_successactionstep_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='successactionstep',
            constraint=models.UniqueConstraint(fields=('tenant', 'plan', 'sequence_order'), name='uq_actionstep_tenant_plan_seq'),
        ),
        migrations.AddConstraint(
            model_name='successactionstep',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_order__gte', 1)), name='chk_actionstep_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='successactionstep',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'CANCELLED'])), name='chk_actionstep_status'),
        ),
        migrations.AddConstraint(
            model_name='successactionstep',
            constraint=models.CheckConstraint(condition=models.Q(('is_authoritative', False)), name='chk_step_non_authoritative'),
        ),
        migrations.AddConstraint(
            model_name='successactionstep',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), ('completed_at__isnull', False)), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='chk_step_completion_consistency'),
        ),
        migrations.AddIndex(
            model_name='successtimelineevent',
            index=models.Index(fields=['tenant', 'plan', '-created_at'], name='idx_timeline_tenant_plan_time'),
        ),
        migrations.AddIndex(
            model_name='successtimelineevent',
            index=models.Index(fields=['tenant', 'target_goal'], name='idx_timeline_tenant_goal'),
        ),
        migrations.AddIndex(
            model_name='successtimelineevent',
            index=models.Index(fields=['tenant', 'target_insight'], name='idx_timeline_tenant_insight'),
        ),
        migrations.AddIndex(
            model_name='successtimelineevent',
            index=models.Index(fields=['tenant', 'target_reflection'], name='idx_timeline_tenant_reflection'),
        ),
        migrations.AddIndex(
            model_name='successtimelineevent',
            index=models.Index(fields=['tenant', 'target_action_step'], name='idx_timeline_tenant_action'),
        ),
        migrations.AddIndex(
            model_name='successtimelineevent',
            index=models.Index(fields=['tenant', 'target_milestone'], name='idx_timeline_tenant_milestone'),
        ),
        migrations.AddIndex(
            model_name='successtimelineevent',
            index=models.Index(fields=['tenant', 'replaces_event'], name='idx_timeline_tenant_replaces'),
        ),
        migrations.AddConstraint(
            model_name='successtimelineevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_successtimelineevent_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='successtimelineevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_mutation_id__isnull', False)), fields=('tenant', 'client_mutation_id'), name='uq_timelineevent_tenant_mutation'),
        ),
        migrations.AddConstraint(
            model_name='successtimelineevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['GOAL_ANCHORED', 'INSIGHT_CONNECTED', 'REFLECTION_TIED', 'ACTION_DISPATCHED', 'MILESTONE_PROGRESSION', 'TIMELINE_EVENT_AMENDED'])), name='chk_timeline_event_type'),
        ),
        migrations.AddIndex(
            model_name='successauditlog',
            index=models.Index(fields=['tenant', 'actor_id', '-created_at'], name='idx_successaudit_tenant_actor'),
        ),
        migrations.AddIndex(
            model_name='successauditlog',
            index=models.Index(fields=['tenant', 'target_plan'], name='idx_successaudit_tenant_plan'),
        ),
        migrations.AddIndex(
            model_name='successauditlog',
            index=models.Index(fields=['tenant', 'target_action_step'], name='idx_successaudit_tenant_act'),
        ),
        migrations.AddIndex(
            model_name='successauditlog',
            index=models.Index(fields=['tenant', 'target_timeline_event'], name='idx_successaudit_tenant_time'),
        ),
        migrations.AddConstraint(
            model_name='successauditlog',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_successauditlog_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='successauditlog',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['CREATE_SUCCESS_PLAN', 'PAUSE_SUCCESS_PLAN', 'RESUME_SUCCESS_PLAN', 'COMPLETE_SUCCESS_PLAN', 'SUPERSEDE_SUCCESS_PLAN', 'ARCHIVE_SUCCESS_PLAN', 'CREATE_ACTION_STEP', 'UPDATE_ACTION_STEP', 'TRANSITION_ACTION_STEP', 'APPEND_TIMELINE_EVENT'])), name='chk_successaudit_action'),
        ),
    ]
