# Generated by Django 5.2.17 on 2026-09-11 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0041_phase3_macro_epic_17_19_operations_rls'),
        ('platform_tenant', '0004_p3_vs12_guardian_access_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurrence_rule', models.CharField(default='WEEKLY', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_cohortschedule',
            },
        ),
        migrations.CreateModel(
            name='CohortScheduleHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('ATTENTION_NEEDED', 'Attention Needed'), ('AT_RISK', 'At Risk'), ('CRITICAL_DELAY', 'Critical Delay')], default='ON_TRACK', max_length=32)),
                ('pending_sessions_count', models.IntegerField(default=0)),
                ('delayed_sessions_count', models.IntegerField(default=0)),
                ('missed_occurrences_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_cohortschedulehealth',
            },
        ),
        migrations.CreateModel(
            name='CourseRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_title', models.CharField(max_length=255)),
                ('release_notes', models.TextField(default='')),
                ('is_active_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_courserelease',
            },
        ),
        migrations.CreateModel(
            name='CurriculumReleaseAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=64)),
                ('previous_state', models.CharField(blank=True, max_length=32, null=True)),
                ('new_state', models.CharField(blank=True, max_length=32, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_curriculumreleaseauditlog',
            },
        ),
        migrations.CreateModel(
            name='CurriculumReleaseCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohorts_adopted_count', models.IntegerField(default=0)),
                ('active_learners_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_curriculumreleasecoverage',
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semver_major', models.IntegerField()),
                ('semver_minor', models.IntegerField()),
                ('semver_patch', models.IntegerField()),
                ('version_tag', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=32)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_curriculumversion',
            },
        ),
        migrations.CreateModel(
            name='DeliveryExceptionQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='OPEN', max_length=32)),
                ('description', models.TextField()),
                ('resolved_by_id', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_deliveryexceptionqueue',
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_title', models.CharField(max_length=255)),
                ('session_order', models.IntegerField(default=1)),
                ('assigned_mentor_id', models.UUIDField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_SESSION', 'In Session'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_learningsession',
            },
        ),
        migrations.CreateModel(
            name='LessonReleaseSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_lesson_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64)),
                ('snapshot_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_lessonreleasesnapshot',
            },
        ),
        migrations.CreateModel(
            name='ModuleReleaseSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('snapshot_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_modulereleasesnapshot',
            },
        ),
        migrations.CreateModel(
            name='ProgramDeliveryAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('completed_sessions', models.IntegerField(default=0)),
                ('cancelled_sessions', models.IntegerField(default=0)),
                ('rescheduled_sessions', models.IntegerField(default=0)),
                ('active_release_version', models.CharField(default='', max_length=32)),
                ('is_authoritative', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'learning_programdeliveryaggregate',
            },
        ),
        migrations.CreateModel(
            name='ReleaseApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_id', models.UUIDField(db_index=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], max_length=32)),
                ('review_comments', models.TextField(default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_releaseapprovalrecord',
            },
        ),
        migrations.CreateModel(
            name='SessionAttendanceState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused'), ('LATE', 'Late')], default='PRESENT', max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_sessionattendancestate',
            },
        ),
        migrations.CreateModel(
            name='SessionChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_by_id', models.UUIDField(db_index=True)),
                ('change_type', models.CharField(choices=[('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('MENTOR_REASSIGNED', 'Mentor Reassigned'), ('TOPIC_UPDATED', 'Topic Updated')], max_length=32)),
                ('original_start', models.DateTimeField(blank=True, null=True)),
                ('new_start', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_sessionchangerecord',
            },
        ),
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('occurrence_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONDUCTED', 'Conducted'), ('MISSED', 'Missed'), ('SUBSTITUTE_CONDUCTED', 'Substitute Conducted')], default='PENDING', max_length=32)),
                ('attendance_count', models.IntegerField(default=0)),
                ('operational_notes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learning_sessionoccurrence',
            },
        ),
        migrations.AddIndex(
            model_name='followupcommitment',
            index=models.Index(fields=['tenant', 'checkin', 'due_date'], name='idx_commitment_checkin_due'),
        ),
        migrations.AddIndex(
            model_name='learningcheckin',
            index=models.Index(fields=['tenant', 'mentor_id', 'scheduled_start'], name='idx_checkin_mentor_sched'),
        ),
        migrations.AddIndex(
            model_name='learningcheckin',
            index=models.Index(fields=['tenant', 'student_id', 'scheduled_start'], name='idx_checkin_student_sched'),
        ),
        migrations.AddIndex(
            model_name='mentorcaseloadassignment',
            index=models.Index(fields=['tenant', 'mentor_id', 'is_active'], name='idx_mentorcaseload_mentor_act'),
        ),
        migrations.AddIndex(
            model_name='mentoroperationsauditlog',
            index=models.Index(fields=['tenant', 'actor_id', '-created_at'], name='idx_mentoropsaudit_actor_time'),
        ),
        migrations.AddIndex(
            model_name='mentoroperationsauditlog',
            index=models.Index(condition=models.Q(('target_caseload__isnull', False)), fields=['tenant', 'target_caseload'], name='idx_mentoropsaudit_caseload'),
        ),
        migrations.AddIndex(
            model_name='mentoroperationsauditlog',
            index=models.Index(condition=models.Q(('target_queue_item__isnull', False)), fields=['tenant', 'target_queue_item'], name='idx_mentoropsaudit_queue'),
        ),
        migrations.AddIndex(
            model_name='mentoroperationsauditlog',
            index=models.Index(condition=models.Q(('target_checkin__isnull', False)), fields=['tenant', 'target_checkin'], name='idx_mentoropsaudit_checkin'),
        ),
        migrations.AddIndex(
            model_name='mentoroperationsauditlog',
            index=models.Index(condition=models.Q(('target_commitment__isnull', False)), fields=['tenant', 'target_commitment'], name='idx_mentoropsaudit_commit'),
        ),
        migrations.AddIndex(
            model_name='mentoroperationsauditlog',
            index=models.Index(condition=models.Q(('target_aggregate__isnull', False)), fields=['tenant', 'target_aggregate'], name='idx_mentoropsaudit_agg'),
        ),
        migrations.AddIndex(
            model_name='programsupportaggregate',
            index=models.Index(fields=['tenant', '-period_start', '-period_end'], name='idx_supportagg_period'),
        ),
        migrations.AddIndex(
            model_name='supportqueueitem',
            index=models.Index(fields=['tenant', 'mentor_id', 'queue_status', 'due_date'], name='idx_supportqueue_mentor_stat'),
        ),
        migrations.AddIndex(
            model_name='supportqueueitem',
            index=models.Index(fields=['tenant', 'student_id'], name='idx_supportqueue_student'),
        ),
        migrations.AddConstraint(
            model_name='followupcommitment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_followupcommitment_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='followupcommitment',
            constraint=models.CheckConstraint(condition=models.Q(('owner_role__in', ['MENTOR', 'STUDENT'])), name='chk_commitment_owner'),
        ),
        migrations.AddConstraint(
            model_name='followupcommitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_completed', False), ('completed_at__isnull', True)), models.Q(('is_completed', True), ('completed_at__isnull', False)), _connector='OR'), name='chk_commitment_completed_order'),
        ),
        migrations.AddConstraint(
            model_name='learningcheckin',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_learningcheckin_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='learningcheckin',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'RESCHEDULED', 'CANCELLED'])), name='chk_checkin_status'),
        ),
        migrations.AddConstraint(
            model_name='learningcheckin',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_start__isnull', True), ('actual_end__isnull', True), ('actual_start__lte', models.F('actual_end')), _connector='OR'), models.Q(('actual_start__isnull', True), ('scheduled_start__lte', models.F('actual_start')), _connector='OR')), name='chk_checkin_timing_order'),
        ),
        migrations.AddConstraint(
            model_name='learningcheckin',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student_acknowledged', False), ('acknowledged_at__isnull', True)), models.Q(('student_acknowledged', True), ('acknowledged_at__isnull', False)), _connector='OR'), name='chk_checkin_acknowledgement'),
        ),
        migrations.AddConstraint(
            model_name='mentorcaseloadassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_mentorcaseload_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='mentorcaseloadassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'student_id'), name='uq_mentorcaseload_active_student'),
        ),
        migrations.AddConstraint(
            model_name='mentorcaseloadassignment',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_weight__gte', 0.1), ('capacity_weight__lte', 5.0)), name='chk_mentorcaseload_weight'),
        ),
        migrations.AddConstraint(
            model_name='mentorcaseloadassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('unassigned_at__isnull', True), ('unassignment_reason__isnull', True)), models.Q(('is_active', False), ('unassigned_at__isnull', False), ('assigned_at__lte', models.F('unassigned_at'))), _connector='OR'), name='chk_mentorcaseload_unassigned_order'),
        ),
        migrations.AddConstraint(
            model_name='mentoroperationsauditlog',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_mentoropsaudit_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='mentoroperationsauditlog',
            constraint=models.CheckConstraint(condition=models.Q(('action_type__in', ['ASSIGN_CASELOAD', 'UNASSIGN_CASELOAD', 'QUEUE_ITEM_PENDING', 'QUEUE_ITEM_IN_REVIEW', 'QUEUE_ITEM_RESOLVED', 'QUEUE_ITEM_DISMISSED', 'SCHEDULE_CHECKIN', 'START_CHECKIN', 'COMPLETE_CHECKIN', 'RESCHEDULE_CHECKIN', 'CANCEL_CHECKIN', 'CREATE_COMMITMENT', 'COMPLETE_COMMITMENT', 'GENERATE_SUPPORT_AGGREGATE'])), name='chk_mentoropsaudit_action_type'),
        ),
        migrations.AddConstraint(
            model_name='programsupportaggregate',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_programsupportaggregate_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='programsupportaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('is_authoritative', False)), name='chk_supportagg_non_authoritative'),
        ),
        migrations.AddConstraint(
            model_name='programsupportaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='chk_supportagg_period_order'),
        ),
        migrations.AddConstraint(
            model_name='supportqueueitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_supportqueueitem_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='supportqueueitem',
            constraint=models.CheckConstraint(condition=models.Q(('source_intervention__isnull', False), ('source_session__isnull', False), _connector='OR'), name='chk_supportqueue_origin_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='supportqueueitem',
            constraint=models.CheckConstraint(condition=models.Q(('urgency_level__in', ['LOW', 'NORMAL', 'HIGH', 'CRITICAL'])), name='chk_supportqueue_urgency'),
        ),
        migrations.AddConstraint(
            model_name='supportqueueitem',
            constraint=models.CheckConstraint(condition=models.Q(('queue_status__in', ['PENDING', 'IN_REVIEW', 'RESOLVED', 'DISMISSED'])), name='chk_supportqueue_status'),
        ),
        migrations.AddConstraint(
            model_name='supportqueueitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('queue_status__in', ['PENDING', 'IN_REVIEW']), ('resolved_at__isnull', True), ('resolution_notes__isnull', True)), models.Q(('queue_status__in', ['RESOLVED', 'DISMISSED']), ('resolved_at__isnull', False)), _connector='OR'), name='chk_supportqueue_resolved_order'),
        ),
        migrations.AddField(
            model_name='cohortschedule',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='learning.cohort'),
        ),
        migrations.AddField(
            model_name='cohortschedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_schedules', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='cohortschedulehealth',
            name='cohort_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_projections', to='learning.cohortschedule'),
        ),
        migrations.AddField(
            model_name='cohortschedulehealth',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_health_projections', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='releases', to='learning.course'),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_releases', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='cohortschedule',
            name='course_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cohort_schedules', to='learning.courserelease'),
        ),
        migrations.AddField(
            model_name='curriculumreleaseauditlog',
            name='course_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='learning.courserelease'),
        ),
        migrations.AddField(
            model_name='curriculumreleaseauditlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_audit_logs', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='curriculumreleasecoverage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_coverages', to='learning.course'),
        ),
        migrations.AddField(
            model_name='curriculumreleasecoverage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_coverages', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='curriculum_versions', to='learning.course'),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_versions', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='curriculumreleasecoverage',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='learning.curriculumversion'),
        ),
        migrations.AddField(
            model_name='curriculumreleaseauditlog',
            name='curriculum_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='learning.curriculumversion'),
        ),
        migrations.AddField(
            model_name='courserelease',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='releases', to='learning.curriculumversion'),
        ),
        migrations.AddField(
            model_name='deliveryexceptionqueue',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='delivery_exceptions', to='learning.cohort'),
        ),
        migrations.AddField(
            model_name='deliveryexceptionqueue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_exceptions', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='cohort_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='learning.cohortschedule'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='deliveryexceptionqueue',
            name='learning_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_exceptions', to='learning.learningsession'),
        ),
        migrations.AddField(
            model_name='lessonreleasesnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_release_snapshots', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='lesson_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='learning.lessonreleasesnapshot'),
        ),
        migrations.AddField(
            model_name='modulereleasesnapshot',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='module_snapshots', to='learning.curriculumversion'),
        ),
        migrations.AddField(
            model_name='modulereleasesnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_release_snapshots', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='lessonreleasesnapshot',
            name='module_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lesson_snapshots', to='learning.modulereleasesnapshot'),
        ),
        migrations.AddField(
            model_name='programdeliveryaggregate',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_aggregates', to='learning.cohort'),
        ),
        migrations.AddField(
            model_name='programdeliveryaggregate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_aggregates', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='releaseapprovalrecord',
            name='curriculum_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approvals', to='learning.curriculumversion'),
        ),
        migrations.AddField(
            model_name='releaseapprovalrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_approvals', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='sessionattendancestate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance_records', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='sessionchangerecord',
            name='learning_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_records', to='learning.learningsession'),
        ),
        migrations.AddField(
            model_name='sessionchangerecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_change_records', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='sessionoccurrence',
            name='learning_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='learning.learningsession'),
        ),
        migrations.AddField(
            model_name='sessionoccurrence',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_occurrences', to='platform_tenant.tenant'),
        ),
        migrations.AddField(
            model_name='sessionattendancestate',
            name='session_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='learning.sessionoccurrence'),
        ),
        migrations.AddIndex(
            model_name='cohortschedulehealth',
            index=models.Index(fields=['tenant', 'health_status'], name='idx_schedhealth_t_status'),
        ),
        migrations.AddConstraint(
            model_name='cohortschedulehealth',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_cohortschedulehealth_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='cohortschedulehealth',
            constraint=models.UniqueConstraint(fields=('tenant', 'cohort_schedule'), name='uq_cohortschedulehealth_schedule'),
        ),
        migrations.AddConstraint(
            model_name='cohortschedulehealth',
            constraint=models.CheckConstraint(condition=models.Q(('health_status__in', ['ON_TRACK', 'ATTENTION_NEEDED', 'AT_RISK', 'CRITICAL_DELAY'])), name='chk_cohortschedulehealth_status'),
        ),
        migrations.AddIndex(
            model_name='cohortschedule',
            index=models.Index(fields=['tenant', 'cohort', 'is_active'], name='idx_cohortsched_t_c_a'),
        ),
        migrations.AddConstraint(
            model_name='cohortschedule',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_cohortschedule_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='cohortschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='chk_cohortschedule_dates_order'),
        ),
        migrations.AddIndex(
            model_name='curriculumversion',
            index=models.Index(fields=['tenant', 'course', 'status'], name='idx_curriculumversion_t_c_s'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_curriculumversion_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'course', 'semver_major', 'semver_minor', 'semver_patch'), name='uq_curriculum_version_tenant_semver'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'RETIRED'])), name='chk_curriculum_version_status'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.CheckConstraint(condition=models.Q(('semver_major__gte', 0), ('semver_minor__gte', 0), ('semver_patch__gte', 0)), name='chk_curriculum_semver_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLISHED'), ('published_at__isnull', False)), models.Q(models.Q(('status', 'PUBLISHED'), _negated=True), ('published_at__isnull', True)), _connector='OR'), name='chk_curriculumversion_published_consistency'),
        ),
        migrations.AddIndex(
            model_name='curriculumreleasecoverage',
            index=models.Index(fields=['tenant', 'course'], name='idx_currcov_t_course'),
        ),
        migrations.AddConstraint(
            model_name='curriculumreleasecoverage',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_curriculumreleasecoverage_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='curriculumreleasecoverage',
            constraint=models.UniqueConstraint(fields=('tenant', 'curriculum_version'), name='uq_releasecoverage_version'),
        ),
        migrations.AddIndex(
            model_name='curriculumreleaseauditlog',
            index=models.Index(fields=['tenant', 'actor_id', '-created_at'], name='idx_curraudit_tenant_actor'),
        ),
        migrations.AddIndex(
            model_name='curriculumreleaseauditlog',
            index=models.Index(condition=models.Q(('curriculum_version__isnull', False)), fields=['tenant', 'curriculum_version'], name='idx_curraudit_version'),
        ),
        migrations.AddIndex(
            model_name='curriculumreleaseauditlog',
            index=models.Index(condition=models.Q(('course_release__isnull', False)), fields=['tenant', 'course_release'], name='idx_curraudit_release'),
        ),
        migrations.AddConstraint(
            model_name='curriculumreleaseauditlog',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_curriculumreleaseauditlog_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='courserelease',
            index=models.Index(fields=['tenant', 'course', 'is_active_default'], name='idx_courserelease_t_c_a'),
        ),
        migrations.AddConstraint(
            model_name='courserelease',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_courserelease_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='deliveryexceptionqueue',
            index=models.Index(fields=['tenant', 'status', 'severity', '-created_at'], name='idx_delexcept_t_s_s_c'),
        ),
        migrations.AddConstraint(
            model_name='deliveryexceptionqueue',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_deliveryexceptionqueue_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='deliveryexceptionqueue',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])), name='chk_deliveryexception_severity'),
        ),
        migrations.AddConstraint(
            model_name='deliveryexceptionqueue',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'INVESTIGATING', 'RESOLVED', 'IGNORED'])), name='chk_deliveryexception_status'),
        ),
        migrations.AddConstraint(
            model_name='deliveryexceptionqueue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['OPEN', 'INVESTIGATING']), ('resolved_at__isnull', True), ('resolved_by_id__isnull', True)), models.Q(('status__in', ['RESOLVED', 'IGNORED']), ('resolved_at__isnull', False)), _connector='OR'), name='chk_deliveryexception_resolved_order'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['tenant', 'cohort_schedule', 'scheduled_start'], name='idx_learnsession_sched_time'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['tenant', 'assigned_mentor_id', 'status'], name='idx_learnsession_mentor_stat'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_learningsession_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_SESSION', 'COMPLETED', 'RESCHEDULED', 'CANCELLED'])), name='chk_learningsession_status'),
        ),
        migrations.AddConstraint(
            model_name='learningsession',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_start__lt', models.F('scheduled_end'))), name='chk_learningsession_timing_order'),
        ),
        migrations.AddIndex(
            model_name='modulereleasesnapshot',
            index=models.Index(fields=['tenant', 'curriculum_version', 'order_index'], name='idx_modulereleasesnap_v_o'),
        ),
        migrations.AddConstraint(
            model_name='modulereleasesnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_modulereleasesnapshot_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='lessonreleasesnapshot',
            index=models.Index(fields=['tenant', 'module_snapshot', 'order_index'], name='idx_lessonreleasesnap_m_o'),
        ),
        migrations.AddConstraint(
            model_name='lessonreleasesnapshot',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_lessonreleasesnapshot_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='programdeliveryaggregate',
            index=models.Index(fields=['tenant', '-computed_at'], name='idx_deliveryagg_t_c'),
        ),
        migrations.AddConstraint(
            model_name='programdeliveryaggregate',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_programdeliveryaggregate_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='programdeliveryaggregate',
            constraint=models.UniqueConstraint(fields=('tenant', 'cohort'), name='uq_deliveryagg_cohort'),
        ),
        migrations.AddConstraint(
            model_name='programdeliveryaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('is_authoritative', False)), name='chk_deliveryagg_non_authoritative'),
        ),
        migrations.AddIndex(
            model_name='releaseapprovalrecord',
            index=models.Index(fields=['tenant', 'curriculum_version', '-reviewed_at'], name='idx_releaseapproval_t_v_t'),
        ),
        migrations.AddConstraint(
            model_name='releaseapprovalrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_releaseapprovalrecord_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='releaseapprovalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['APPROVED', 'REJECTED', 'CHANGES_REQUESTED'])), name='chk_releaseapproval_decision'),
        ),
        migrations.AddIndex(
            model_name='sessionchangerecord',
            index=models.Index(fields=['tenant', 'learning_session', '-created_at'], name='idx_sesschange_t_s_c'),
        ),
        migrations.AddConstraint(
            model_name='sessionchangerecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_sessionchangerecord_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='sessionchangerecord',
            constraint=models.CheckConstraint(condition=models.Q(('change_type__in', ['RESCHEDULED', 'CANCELLED', 'MENTOR_REASSIGNED', 'TOPIC_UPDATED'])), name='chk_sessionchange_type'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['tenant', 'learning_session', 'actual_start'], name='idx_sessoccur_t_s_a'),
        ),
        migrations.AddConstraint(
            model_name='sessionoccurrence',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_sessionoccurrence_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='sessionoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('occurrence_status__in', ['PENDING', 'CONDUCTED', 'MISSED', 'SUBSTITUTE_CONDUCTED'])), name='chk_sessionoccurrence_status'),
        ),
        migrations.AddConstraint(
            model_name='sessionoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('actual_start__isnull', True), ('actual_end__isnull', True), ('actual_start__lte', models.F('actual_end')), _connector='OR'), name='chk_session_timing_order'),
        ),
        migrations.AddIndex(
            model_name='sessionattendancestate',
            index=models.Index(fields=['tenant', 'student_id', 'status'], name='idx_sessattendance_t_s_s'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendancestate',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_sessionattendancestate_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendancestate',
            constraint=models.UniqueConstraint(fields=('tenant', 'session_occurrence', 'student_id'), name='uq_session_attendance_student'),
        ),
        migrations.AddConstraint(
            model_name='sessionattendancestate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PRESENT', 'ABSENT', 'EXCUSED', 'LATE'])), name='chk_sessionattendance_status'),
        ),
    ]
