# Generated by Django 5.2.17 on 2026-09-11 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0043_phase3_macro_epic_20_22_rls'),
        ('platform_tenant', '0004_p3_vs12_guardian_access_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blueprint_title', models.CharField(max_length=255)),
                ('version_tag', models.CharField(default='v1.0', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('SUPERSEDED', 'Superseded'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=32)),
                ('pedagogical_intent', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assessment_blueprints', to='learning.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_blueprints', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_assessmentblueprint',
            },
        ),
        migrations.CreateModel(
            name='CohortRollforwardPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rollforward_mode', models.CharField(choices=[('FUTURE_MODULES_ONLY', 'Future Modules Only'), ('NEXT_COHORT_ONLY', 'Next Cohort Only'), ('EXPLICIT_APPROVAL_REQUIRED', 'Explicit Approval Required')], default='FUTURE_MODULES_ONLY', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('scheduled_effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort_schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rollforward_plans', to='learning.cohortschedule')),
                ('target_release', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rollforward_plans', to='learning.courserelease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_rollforward_plans', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_cohortrollforwardplan',
            },
        ),
        migrations.CreateModel(
            name='ContentChangeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('change_summary', models.TextField(default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('MERGED_TO_RELEASE', 'Merged to Release')], default='DRAFT', max_length=32)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_change_sets', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_contentchangeset',
            },
        ),
        migrations.CreateModel(
            name='ChangeApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approver_id', models.UUIDField(blank=True, null=True)),
                ('approval_verdict', models.CharField(choices=[('APPROVED', 'Approved'), ('CONDITIONALLY_APPROVED', 'Conditionally Approved')], max_length=32)),
                ('approval_hash', models.CharField(max_length=64)),
                ('justification', models.TextField(default='')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_approval_records', to='platform_tenant.tenant')),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approvals', to='learning.contentchangeset')),
            ],
            options={
                'db_table': 'learning_changeapprovalrecord',
            },
        ),
        migrations.CreateModel(
            name='CurriculumChangeImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_level', models.CharField(choices=[('PATCH', 'Patch'), ('MINOR', 'Minor'), ('MAJOR', 'Major'), ('BREAKING', 'Breaking')], default='MINOR', max_length=32)),
                ('breaking_changes_detected', models.BooleanField(default=False)),
                ('affected_cohorts_count', models.IntegerField(default=0)),
                ('impact_details', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='source_impact_analyses', to='learning.curriculumversion')),
                ('target_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='target_impact_analyses', to='learning.curriculumversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_change_impacts', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_curriculumchangeimpact',
            },
        ),
        migrations.CreateModel(
            name='CurriculumDraftWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUBMITTED', 'Submitted'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=32)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='derived_workspaces', to='learning.curriculumversion')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='draft_workspaces', to='learning.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_draft_workspaces', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_curriculumdraftworkspace',
            },
        ),
        migrations.AddField(
            model_name='contentchangeset',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_sets', to='learning.curriculumdraftworkspace'),
        ),
        migrations.CreateModel(
            name='AuthorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('assigned_role', models.CharField(choices=[('PRIMARY_AUTHOR', 'Primary Author'), ('CONTRIBUTOR', 'Contributor'), ('CURATOR', 'Curator')], default='PRIMARY_AUTHOR', max_length=32)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_assignments', to='platform_tenant.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.curriculumdraftworkspace')),
            ],
            options={
                'db_table': 'learning_authorassignment',
            },
        ),
        migrations.CreateModel(
            name='CurriculumMigrationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decided_by_id', models.UUIDField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('PROCEED', 'Proceed'), ('HALT', 'Halt'), ('EXCEPTION_REQUIRED', 'Exception Required')], max_length=32)),
                ('justification', models.TextField(default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='migration_decisions', to='learning.cohortrollforwardplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_migration_decisions', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_curriculummigrationdecision',
            },
        ),
        migrations.CreateModel(
            name='EditorialReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_id', models.UUIDField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('review_notes', models.TextField(default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_reviews', to='learning.contentchangeset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_reviews', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_editorialreview',
            },
        ),
        migrations.CreateModel(
            name='LearningObjectiveMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective_code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('bloom_taxonomy_level', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('APPLY', 'Apply'), ('ANALYZE', 'Analyze'), ('EVALUATE', 'Evaluate'), ('CREATE', 'Create')], default='APPLY', max_length=32)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_mappings', to='learning.assessmentblueprint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objective_mappings', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_learningobjectivemapping',
            },
        ),
        migrations.CreateModel(
            name='ReleaseReadinessCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=128)),
                ('category', models.CharField(default='EDITORIAL', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WAIVED', 'Waived')], default='PENDING', max_length=32)),
                ('check_output', models.TextField(default='')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_checks', to='learning.curriculumversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_readiness_checks', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_releasereadinesscheck',
            },
        ),
        migrations.CreateModel(
            name='ReleaseReadinessGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_name', models.CharField(max_length=128)),
                ('is_blocking', models.BooleanField(default=True)),
                ('verdict', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WAIVED', 'Waived')], default='PENDING', max_length=32)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_gates', to='learning.curriculumversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_readiness_gates', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_releasereadinessgate',
            },
        ),
        migrations.CreateModel(
            name='ReleaseExceptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_by_id', models.UUIDField(blank=True, null=True)),
                ('exception_reason', models.TextField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_exception_records', to='platform_tenant.tenant')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exceptions', to='learning.releasereadinessgate')),
            ],
            options={
                'db_table': 'learning_releaseexceptionrecord',
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('comment_text', models.TextField()),
                ('target_entity', models.CharField(max_length=64)),
                ('target_entity_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learning.editorialreview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_reviewcomment',
            },
        ),
        migrations.CreateModel(
            name='ReviewResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolver_id', models.UUIDField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('WAIVED', 'Waived'), ('DEFERRED', 'Deferred')], default='RESOLVED', max_length=32)),
                ('resolution_notes', models.TextField(default='')),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='learning.editorialreview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_resolutions', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_reviewresolution',
            },
        ),
        migrations.CreateModel(
            name='RubricDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rubric_title', models.CharField(max_length=255)),
                ('scale_type', models.CharField(default='QUALITATIVE_STANDARD', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('RETIRED', 'Retired')], default='DRAFT', max_length=32)),
                ('is_anti_ranking_compliant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rubrics', to='learning.assessmentblueprint')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_definitions', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_rubricdefinition',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion_title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evaluation_levels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='platform_tenant.tenant')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='learning.rubricdefinition')),
            ],
            options={
                'db_table': 'learning_rubriccriterion',
            },
        ),
        migrations.CreateModel(
            name='AssessmentReleaseBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_authoritative', models.BooleanField(default=True)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='release_bindings', to='learning.assessmentblueprint')),
                ('course_release', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assessment_bindings', to='learning.courserelease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_release_bindings', to='platform_tenant.tenant')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='release_bindings', to='learning.rubricdefinition')),
            ],
            options={
                'db_table': 'learning_assessmentreleasebinding',
            },
        ),
        migrations.CreateModel(
            name='RubricReviewRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_id', models.UUIDField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revision Requested')], max_length=32)),
                ('pedagogical_notes', models.TextField(default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviews', to='learning.rubricdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_review_records', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_rubricreviewrecord',
            },
        ),
        migrations.AddIndex(
            model_name='assessmentblueprint',
            index=models.Index(fields=['tenant', 'course', 'status'], name='idx_assessbp_t_c_s'),
        ),
        migrations.AddConstraint(
            model_name='assessmentblueprint',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_assessmentblueprint_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='assessmentblueprint',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'DRAFT', 'SUPERSEDED', 'RETIRED'])), name='chk_assessmentblueprint_status'),
        ),
        migrations.AddConstraint(
            model_name='cohortrollforwardplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_cohortrollforwardplan_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='cohortrollforwardplan',
            constraint=models.CheckConstraint(condition=models.Q(('rollforward_mode__in', ['FUTURE_MODULES_ONLY', 'NEXT_COHORT_ONLY', 'EXPLICIT_APPROVAL_REQUIRED'])), name='chk_cohortrollforward_mode'),
        ),
        migrations.AddConstraint(
            model_name='cohortrollforwardplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'APPROVED', 'APPLIED', 'CANCELLED'])), name='chk_cohortrollforward_status'),
        ),
        migrations.AddIndex(
            model_name='changeapprovalrecord',
            index=models.Index(fields=['tenant', 'change_set'], name='idx_changeappr_t_cs'),
        ),
        migrations.AddIndex(
            model_name='changeapprovalrecord',
            index=models.Index(fields=['tenant', 'approver_id'], name='idx_changeappr_t_a'),
        ),
        migrations.AddConstraint(
            model_name='changeapprovalrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_changeapprovalrecord_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='changeapprovalrecord',
            constraint=models.CheckConstraint(condition=models.Q(('approval_verdict__in', ['APPROVED', 'CONDITIONALLY_APPROVED'])), name='chk_changeapproval_verdict'),
        ),
        migrations.AddConstraint(
            model_name='curriculumchangeimpact',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_curriculumchangeimpact_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='curriculumchangeimpact',
            constraint=models.CheckConstraint(condition=models.Q(('impact_level__in', ['PATCH', 'MINOR', 'MAJOR', 'BREAKING'])), name='chk_changeimpact_level'),
        ),
        migrations.AddIndex(
            model_name='curriculumdraftworkspace',
            index=models.Index(fields=['tenant', 'course', 'status'], name='idx_draftws_t_c_s'),
        ),
        migrations.AddConstraint(
            model_name='curriculumdraftworkspace',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_curriculumdraftworkspace_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='curriculumdraftworkspace',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'SUBMITTED', 'ARCHIVED'])), name='chk_draftworkspace_status'),
        ),
        migrations.AddIndex(
            model_name='contentchangeset',
            index=models.Index(fields=['tenant', 'workspace', 'status'], name='idx_cchangeset_t_w_s'),
        ),
        migrations.AddConstraint(
            model_name='contentchangeset',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_contentchangeset_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='contentchangeset',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'IN_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'MERGED_TO_RELEASE'])), name='chk_contentchangeset_status'),
        ),
        migrations.AddConstraint(
            model_name='authorassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_authorassignment_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='authorassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'workspace', 'author_id'), name='uq_authorassignment_workspace_author'),
        ),
        migrations.AddConstraint(
            model_name='authorassignment',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_role__in', ['PRIMARY_AUTHOR', 'CONTRIBUTOR', 'CURATOR'])), name='chk_authorassignment_role'),
        ),
        migrations.AddIndex(
            model_name='curriculummigrationdecision',
            index=models.Index(fields=['tenant', 'plan'], name='idx_migdecision_t_p'),
        ),
        migrations.AddIndex(
            model_name='curriculummigrationdecision',
            index=models.Index(fields=['tenant', 'decided_by_id'], name='idx_migdecision_t_d'),
        ),
        migrations.AddConstraint(
            model_name='curriculummigrationdecision',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_curriculummigrationdecision_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='curriculummigrationdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['PROCEED', 'HALT', 'EXCEPTION_REQUIRED'])), name='chk_migrationdecision_decision'),
        ),
        migrations.AddIndex(
            model_name='editorialreview',
            index=models.Index(fields=['tenant', 'change_set', 'decision'], name='idx_edreview_t_cs_d'),
        ),
        migrations.AddConstraint(
            model_name='editorialreview',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_editorialreview_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='editorialreview',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['PENDING', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'REJECTED'])), name='chk_editorialreview_decision'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectivemapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_learningobjectivemapping_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectivemapping',
            constraint=models.CheckConstraint(condition=models.Q(('weight_percentage__gt', 0), ('weight_percentage__lte', 100.0)), name='chk_objectivemapping_weight'),
        ),
        migrations.AddConstraint(
            model_name='learningobjectivemapping',
            constraint=models.CheckConstraint(condition=models.Q(('bloom_taxonomy_level__in', ['REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE'])), name='chk_objectivemapping_taxonomy'),
        ),
        migrations.AddConstraint(
            model_name='releasereadinesscheck',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_releasereadinesscheck_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='releasereadinesscheck',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PASSED', 'FAILED', 'WAIVED'])), name='chk_readinesscheck_status'),
        ),
        migrations.AddConstraint(
            model_name='releasereadinessgate',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_releasereadinessgate_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='releasereadinessgate',
            constraint=models.UniqueConstraint(fields=('tenant', 'curriculum_version', 'gate_name'), name='uq_gate_version_name'),
        ),
        migrations.AddConstraint(
            model_name='releasereadinessgate',
            constraint=models.CheckConstraint(condition=models.Q(('verdict__in', ['PENDING', 'PASSED', 'FAILED', 'WAIVED'])), name='chk_readinessgate_verdict'),
        ),
        migrations.AddIndex(
            model_name='releaseexceptionrecord',
            index=models.Index(fields=['tenant', 'gate'], name='idx_relexcept_t_g'),
        ),
        migrations.AddIndex(
            model_name='releaseexceptionrecord',
            index=models.Index(fields=['tenant', 'granted_by_id'], name='idx_relexcept_t_grantor'),
        ),
        migrations.AddConstraint(
            model_name='releaseexceptionrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_releaseexceptionrecord_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='reviewcomment',
            index=models.Index(fields=['tenant', 'review', '-created_at'], name='idx_revcomment_t_r_c'),
        ),
        migrations.AddConstraint(
            model_name='reviewcomment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_reviewcomment_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='reviewresolution',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_reviewresolution_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='reviewresolution',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_status__in', ['RESOLVED', 'WAIVED', 'DEFERRED'])), name='chk_reviewresolution_status'),
        ),
        migrations.AddIndex(
            model_name='rubricdefinition',
            index=models.Index(fields=['tenant', 'blueprint', 'status'], name='idx_rubricdef_t_bp_s'),
        ),
        migrations.AddConstraint(
            model_name='rubricdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_rubricdefinition_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='rubricdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'SUPERSEDED', 'RETIRED'])), name='chk_rubricdefinition_status'),
        ),
        migrations.AddConstraint(
            model_name='rubricdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('is_anti_ranking_compliant', True)), name='chk_rubric_anti_ranking'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_rubriccriterion_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight_percentage__gt', 0), ('weight_percentage__lte', 100.0)), name='chk_rubriccriterion_weight'),
        ),
        migrations.AddConstraint(
            model_name='assessmentreleasebinding',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_assessmentreleasebinding_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='assessmentreleasebinding',
            constraint=models.UniqueConstraint(fields=('tenant', 'course_release', 'blueprint'), name='uq_binding_release_blueprint'),
        ),
        migrations.AddIndex(
            model_name='rubricreviewrecord',
            index=models.Index(fields=['tenant', 'rubric'], name='idx_rubricrev_t_r'),
        ),
        migrations.AddIndex(
            model_name='rubricreviewrecord',
            index=models.Index(fields=['tenant', 'reviewer_id'], name='idx_rubricrev_t_rev'),
        ),
        migrations.AddConstraint(
            model_name='rubricreviewrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_rubricreviewrecord_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='rubricreviewrecord',
            constraint=models.CheckConstraint(condition=models.Q(('verdict__in', ['APPROVED', 'REVISION_REQUESTED'])), name='chk_rubricreview_verdict'),
        ),
    ]
