# Generated by Django 5.2.17 on 2026-09-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0045_p3_macro_epic_23_25_rls_force'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentblueprint',
            name='pedagogical_intent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='changeapprovalrecord',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contentchangeset',
            name='change_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='curriculumchangeimpact',
            name='impact_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='curriculumdraftworkspace',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='curriculummigrationdecision',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='editorialreview',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='releasereadinesscheck',
            name='check_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reviewresolution',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rubriccriterion',
            name='evaluation_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='rubricreviewrecord',
            name='pedagogical_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
