# Generated by Django 5.2.17 on 2026-09-11 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0046_update_p3_macro_epic_23_25_blank_fields'),
        ('platform_tenant', '0004_p3_vs12_guardian_access_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('campaign_period', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONCLUDED', 'Concluded'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=32)),
                ('deadline', models.DateTimeField()),
                ('created_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_review_campaigns', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_access_review_campaign',
            },
        ),
        migrations.CreateModel(
            name='DataDispositionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_applied', models.CharField(choices=[('ANONYMIZE', 'Anonymize'), ('PURGE', 'Purge'), ('ARCHIVE', 'Archive')], max_length=32)),
                ('status', models.CharField(default='EXECUTED', max_length=32)),
                ('records_processed', models.IntegerField(default=0)),
                ('cryptographic_digest', models.CharField(max_length=128)),
                ('executed_by_id', models.UUIDField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_disposition_records', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_data_disposition_record',
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_category', models.CharField(max_length=64)),
                ('retention_period_days', models.IntegerField()),
                ('disposition_action', models.CharField(choices=[('ANONYMIZE', 'Anonymize'), ('PURGE', 'Purge'), ('ARCHIVE', 'Archive')], default='ANONYMIZE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_retention_policies', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_data_retention_policy',
            },
        ),
        migrations.CreateModel(
            name='DispositionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_key_hash', models.CharField(max_length=128)),
                ('status', models.CharField(default='SUCCESS', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disposition_record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audit_logs', to='learning.datadispositionrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_audit_logs', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_disposition_audit_log',
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('legal_case_reference', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], default='ACTIVE', max_length=32)),
                ('placed_by_id', models.UUIDField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('released_by_id', models.UUIDField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_legal_hold',
            },
        ),
        migrations.CreateModel(
            name='LegalHoldScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_entity_type', models.CharField(max_length=64)),
                ('target_entity_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='learning.legalhold')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_hold_scopes', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_legal_hold_scope',
            },
        ),
        migrations.CreateModel(
            name='PilotReadinessGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_verdict', models.CharField(choices=[('READY', 'Ready'), ('NOT_READY', 'Not Ready'), ('BLOCKED', 'Blocked'), ('EXCEPTION_REQUIRED', 'Exception Required')], max_length=32)),
                ('status', models.CharField(default='EVALUATED', max_length=32)),
                ('human_attestation_summary', models.TextField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_readiness_gates', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_pilot_readiness_gate',
            },
        ),
        migrations.CreateModel(
            name='ControlAttestationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attested_by_id', models.UUIDField()),
                ('attestation_role', models.CharField(max_length=64)),
                ('signature_digest', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_attestation_audits', to='platform_tenant.tenant')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attestations', to='learning.pilotreadinessgate')),
            ],
            options={
                'db_table': 'learning_control_attestation_audit',
            },
        ),
        migrations.CreateModel(
            name='PrivilegedActionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('action_type', models.CharField(max_length=64)),
                ('target_resource', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileged_action_audits', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_privileged_action_audit',
            },
        ),
        migrations.CreateModel(
            name='PrivilegedPermissionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('permission_code', models.CharField(max_length=64)),
                ('justification', models.TextField()),
                ('granted_by_id', models.UUIDField()),
                ('second_approver_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileged_permission_grants', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_privileged_permission_grant',
            },
        ),
        migrations.CreateModel(
            name='ReadinessAssessmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_reference', models.CharField(max_length=64)),
                ('total_controls', models.IntegerField(default=0)),
                ('passed_controls', models.IntegerField(default=0)),
                ('failed_controls', models.IntegerField(default=0)),
                ('overall_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('NOT_READY', 'Not Ready'), ('BLOCKED', 'Blocked'), ('EXCEPTION_REQUIRED', 'Exception Required')], default='IN_PROGRESS', max_length=32)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=32)),
                ('executed_by_id', models.UUIDField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_assessment_runs', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_readiness_assessment_run',
            },
        ),
        migrations.AddField(
            model_name='pilotreadinessgate',
            name='assessment_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pilot_gates', to='learning.readinessassessmentrun'),
        ),
        migrations.CreateModel(
            name='ReadinessControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_code', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('SECURITY', 'Security'), ('DATA_GOVERNANCE', 'Data Governance'), ('TESTING', 'Testing'), ('RLS', 'RLS'), ('FLEET', 'Fleet')], max_length=64)),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_controls', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_readiness_control',
            },
        ),
        migrations.CreateModel(
            name='ReadinessEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(max_length=64)),
                ('artifact_reference', models.CharField(max_length=255)),
                ('verification_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('SUPERSEDED', 'Superseded'), ('REVOKED', 'Revoked')], default='VALID', max_length=32)),
                ('recorded_by_id', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evidences', to='learning.readinesscontrol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_evidences', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_readiness_evidence',
            },
        ),
        migrations.CreateModel(
            name='ReadinessFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('BLOCKER', 'Blocker'), ('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], default='MAJOR', max_length=32)),
                ('finding_summary', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=32)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='learning.readinessassessmentrun')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='findings', to='learning.readinesscontrol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_findings', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_readiness_finding',
            },
        ),
        migrations.CreateModel(
            name='ReadinessException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('expiry_date', models.DateTimeField()),
                ('approved_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_exceptions', to='platform_tenant.tenant')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exceptions', to='learning.readinessfinding')),
            ],
            options={
                'db_table': 'learning_readiness_exception',
            },
        ),
        migrations.CreateModel(
            name='RetentionEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluated_entity_type', models.CharField(max_length=64)),
                ('candidates_count', models.IntegerField(default=0)),
                ('exempted_by_legal_hold_count', models.IntegerField(default=0)),
                ('disposition_ready_count', models.IntegerField(default=0)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='evaluations', to='learning.dataretentionpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_evaluations', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_retention_evaluation',
            },
        ),
        migrations.AddField(
            model_name='datadispositionrecord',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='disposition_records', to='learning.retentionevaluation'),
        ),
        migrations.CreateModel(
            name='RetentionPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('retention_period_days', models.IntegerField()),
                ('disposition_action', models.CharField(choices=[('ANONYMIZE', 'Anonymize'), ('PURGE', 'Purge'), ('ARCHIVE', 'Archive')], max_length=32)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='learning.dataretentionpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy_versions', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_retention_policy_version',
            },
        ),
        migrations.CreateModel(
            name='StaffAccessAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('role_name', models.CharField(choices=[('TENANT_ADMIN', 'Tenant Admin'), ('DELEGATED_STAFF', 'Delegated Staff'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('AUDITOR', 'Auditor'), ('PROGRAM_OPERATOR', 'Program Operator')], max_length=64)),
                ('scope_type', models.CharField(default='TENANT_WIDE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('assigned_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access_assignments', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_staff_access_assignment',
            },
        ),
        migrations.CreateModel(
            name='DelegatedAdminScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_resource_type', models.CharField(choices=[('BRANCH', 'Branch'), ('PROGRAM', 'Program'), ('DEPARTMENT', 'Department'), ('COHORT', 'Cohort')], max_length=64)),
                ('scope_resource_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegated_admin_scopes', to='platform_tenant.tenant')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='learning.staffaccessassignment')),
            ],
            options={
                'db_table': 'learning_delegated_admin_scope',
            },
        ),
        migrations.CreateModel(
            name='AccessReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_id', models.UUIDField()),
                ('decision', models.CharField(choices=[('MAINTAIN', 'Maintain'), ('REVOKE', 'Revoke'), ('RESTRICT', 'Restrict')], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='learning.accessreviewcampaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_review_decisions', to='platform_tenant.tenant')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='learning.staffaccessassignment')),
            ],
            options={
                'db_table': 'learning_access_review_decision',
            },
        ),
        migrations.AddIndex(
            model_name='accessreviewcampaign',
            index=models.Index(fields=['tenant', 'status'], name='idx_acc_camp_t_stat'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewcampaign',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_access_review_campaign_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'CONCLUDED', 'CANCELLED'])), name='chk_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='dataretentionpolicy',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_ret_pol_t_act'),
        ),
        migrations.AddConstraint(
            model_name='dataretentionpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_data_retention_policy_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='dataretentionpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'data_category'), name='uq_retention_category'),
        ),
        migrations.AddConstraint(
            model_name='dataretentionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('retention_period_days__gte', 30)), name='chk_retention_period_positive'),
        ),
        migrations.AddConstraint(
            model_name='dataretentionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('disposition_action__in', ['ANONYMIZE', 'PURGE', 'ARCHIVE'])), name='chk_disposition_action'),
        ),
        migrations.AddIndex(
            model_name='dispositionauditlog',
            index=models.Index(fields=['tenant', 'actor_id', '-created_at'], name='idx_disp_audit_t_act_cr'),
        ),
        migrations.AddConstraint(
            model_name='dispositionauditlog',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_disposition_audit_log_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='legalhold',
            index=models.Index(fields=['tenant', 'status'], name='idx_legal_hold_t_stat'),
        ),
        migrations.AddConstraint(
            model_name='legalhold',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_legal_hold_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='legalhold',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'RELEASED'])), name='chk_hold_status'),
        ),
        migrations.AddConstraint(
            model_name='legalhold',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RELEASED'), ('released_at__isnull', False), ('released_by_id__isnull', False)), models.Q(('status', 'ACTIVE'), ('released_at__isnull', True), ('released_by_id__isnull', True)), _connector='OR'), name='chk_hold_release_consistency'),
        ),
        migrations.AddIndex(
            model_name='legalholdscope',
            index=models.Index(fields=['tenant', 'legal_hold'], name='idx_legal_scope_t_hold'),
        ),
        migrations.AddConstraint(
            model_name='legalholdscope',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_legal_hold_scope_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='controlattestationaudit',
            index=models.Index(fields=['tenant', 'gate', '-created_at'], name='idx_ctrl_attest_t_g_cr'),
        ),
        migrations.AddConstraint(
            model_name='controlattestationaudit',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_control_attestation_audit_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='privilegedactionaudit',
            index=models.Index(fields=['tenant', 'actor_id', '-created_at'], name='idx_priv_audit_t_act_cr'),
        ),
        migrations.AddConstraint(
            model_name='privilegedactionaudit',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_privileged_action_audit_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='privilegedpermissiongrant',
            index=models.Index(fields=['tenant', 'user_id', 'status'], name='idx_priv_grant_t_u_stat'),
        ),
        migrations.AddConstraint(
            model_name='privilegedpermissiongrant',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_privileged_permission_grant_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='privilegedpermissiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('user_id', models.F('granted_by_id')), _negated=True), name='chk_privilege_no_self_grant'),
        ),
        migrations.AddConstraint(
            model_name='privilegedpermissiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('second_approver_id__isnull', True), models.Q(('second_approver_id', models.F('granted_by_id')), _negated=True), _connector='OR'), name='chk_privilege_distinct_second_approver'),
        ),
        migrations.AddConstraint(
            model_name='privilegedpermissiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'EXPIRED', 'REVOKED'])), name='chk_privilege_status'),
        ),
        migrations.AddIndex(
            model_name='readinessassessmentrun',
            index=models.Index(fields=['tenant', 'status'], name='idx_read_run_t_stat'),
        ),
        migrations.AddConstraint(
            model_name='readinessassessmentrun',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_readiness_assessment_run_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='readinessassessmentrun',
            constraint=models.CheckConstraint(condition=models.Q(('overall_status__in', ['IN_PROGRESS', 'READY', 'NOT_READY', 'BLOCKED', 'EXCEPTION_REQUIRED'])), name='chk_run_status'),
        ),
        migrations.AddIndex(
            model_name='pilotreadinessgate',
            index=models.Index(fields=['tenant', 'status'], name='idx_pilot_gate_t_stat'),
        ),
        migrations.AddConstraint(
            model_name='pilotreadinessgate',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_pilot_readiness_gate_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='pilotreadinessgate',
            constraint=models.CheckConstraint(condition=models.Q(('gate_verdict__in', ['READY', 'NOT_READY', 'BLOCKED', 'EXCEPTION_REQUIRED'])), name='chk_gate_verdict'),
        ),
        migrations.AddIndex(
            model_name='readinesscontrol',
            index=models.Index(fields=['tenant', 'category'], name='idx_read_ctrl_t_cat'),
        ),
        migrations.AddConstraint(
            model_name='readinesscontrol',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_readiness_control_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='readinesscontrol',
            constraint=models.UniqueConstraint(fields=('tenant', 'control_code'), name='uq_readiness_control_code'),
        ),
        migrations.AddConstraint(
            model_name='readinesscontrol',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['SECURITY', 'DATA_GOVERNANCE', 'TESTING', 'RLS', 'FLEET'])), name='chk_control_category'),
        ),
        migrations.AddConstraint(
            model_name='readinessevidence',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_readiness_evidence_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='readinessevidence',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['VALID', 'SUPERSEDED', 'REVOKED'])), name='chk_evidence_status'),
        ),
        migrations.AddIndex(
            model_name='readinessfinding',
            index=models.Index(fields=['tenant', 'severity', 'status'], name='idx_read_find_t_sev_stat'),
        ),
        migrations.AddConstraint(
            model_name='readinessfinding',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_readiness_finding_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='readinessfinding',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR'])), name='chk_finding_severity'),
        ),
        migrations.AddConstraint(
            model_name='readinessexception',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_readiness_exception_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='retentionevaluation',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_retention_evaluation_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='datadispositionrecord',
            index=models.Index(fields=['tenant', 'status'], name='idx_disp_rec_t_stat'),
        ),
        migrations.AddConstraint(
            model_name='datadispositionrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_data_disposition_record_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='retentionpolicyversion',
            index=models.Index(fields=['tenant', 'policy', '-version_number'], name='idx_ret_ver_t_pol_v'),
        ),
        migrations.AddConstraint(
            model_name='retentionpolicyversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_retention_policy_version_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='retentionpolicyversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'policy', 'version_number'), name='uq_policy_version'),
        ),
        migrations.AddIndex(
            model_name='staffaccessassignment',
            index=models.Index(fields=['tenant', 'user_id', 'is_active'], name='idx_staff_assign_t_u_act'),
        ),
        migrations.AddConstraint(
            model_name='staffaccessassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_staff_access_assignment_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='staffaccessassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'user_id', 'role_name'), name='uq_staff_assignment'),
        ),
        migrations.AddConstraint(
            model_name='staffaccessassignment',
            constraint=models.CheckConstraint(condition=models.Q(('role_name__in', ['TENANT_ADMIN', 'DELEGATED_STAFF', 'COMPLIANCE_OFFICER', 'AUDITOR', 'PROGRAM_OPERATOR'])), name='chk_staff_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='staffaccessassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='chk_staff_validity_window'),
        ),
        migrations.AddIndex(
            model_name='delegatedadminscope',
            index=models.Index(fields=['tenant', 'assignment'], name='idx_del_admin_scope_t_assign'),
        ),
        migrations.AddConstraint(
            model_name='delegatedadminscope',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_delegated_admin_scope_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='delegatedadminscope',
            constraint=models.CheckConstraint(condition=models.Q(('scope_resource_type__in', ['BRANCH', 'PROGRAM', 'DEPARTMENT', 'COHORT'])), name='chk_scope_resource_type'),
        ),
        migrations.AddIndex(
            model_name='accessreviewdecision',
            index=models.Index(fields=['tenant', 'campaign', 'reviewer_id'], name='idx_rev_dec_t_camp_rev'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewdecision',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_access_review_decision_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewdecision',
            constraint=models.UniqueConstraint(fields=('tenant', 'campaign', 'assignment'), name='uq_review_decision_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewdecision',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['MAINTAIN', 'REVOKE', 'RESTRICT'])), name='chk_review_decision'),
        ),
    ]
