# Generated by Django 5.2.17 on 2026-09-13 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0048_p3_macro_epic_26_28_rls_force'),
        ('platform_tenant', '0004_p3_vs12_guardian_access_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('SEV1', 'SEV1 - Multi-Tenant / Outage'), ('SEV2', 'SEV2 - Critical Learning Blocker'), ('SEV3', 'SEV3 - Moderate Performance'), ('SEV4', 'SEV4 - Minor Issue')], default='SEV3', max_length=16)),
                ('state', models.CharField(choices=[('DETECTED', 'Detected'), ('TRIAGED', 'Triaged'), ('INVESTIGATING', 'Investigating'), ('MITIGATED', 'Mitigated'), ('RESOLVED', 'Resolved')], default='DETECTED', max_length=32)),
                ('summary', models.TextField()),
                ('assigned_operator_id', models.UUIDField(blank=True, null=True)),
                ('post_incident_review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_incident_record',
                'indexes': [models.Index(fields=['tenant', 'state', 'severity'], name='idx_incident_t_st_sev')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_incident_record_tenant_id'), models.UniqueConstraint(fields=('tenant', 'incident_number'), name='uq_learning_incident_number'), models.CheckConstraint(condition=models.Q(('severity__in', ['SEV1', 'SEV2', 'SEV3', 'SEV4'])), name='chk_incident_severity_valid'), models.CheckConstraint(condition=models.Q(('state__in', ['DETECTED', 'TRIAGED', 'INVESTIGATING', 'MITIGATED', 'RESOLVED'])), name='chk_incident_state_valid')],
            },
        ),
        migrations.CreateModel(
            name='PilotTenantProvisioningPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(max_length=64)),
                ('organization_name', models.CharField(max_length=128)),
                ('status', models.CharField(default='PLANNED', max_length=32)),
                ('is_synthetic_only', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_provisioning_plans', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_pilot_tenant_provisioning_plan',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_pilot_provisioning_plan_tenant_id'), models.CheckConstraint(condition=models.Q(('is_synthetic_only', True)), name='chk_pilot_synthetic_data_only')],
            },
        ),
        migrations.CreateModel(
            name='ReleaseCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=64)),
                ('commit_sha', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('CANDIDATE_TAGGED', 'Candidate Tagged'), ('VERIFIED_ON_STAGING', 'Verified On Staging'), ('PILOT_DEPLOYED', 'Pilot Deployed'), ('ABORTED', 'Aborted'), ('ROLLED_BACK', 'Rolled Back')], default='DRAFT', max_length=32)),
                ('is_production_target', models.BooleanField(default=False)),
                ('has_dual_custody_approval', models.BooleanField(default=False)),
                ('created_by_id', models.UUIDField()),
                ('approved_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_candidates', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_release_candidate',
                'indexes': [models.Index(fields=['tenant', 'state'], name='idx_rc_t_state')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_release_candidate_tenant_id'), models.UniqueConstraint(fields=('tenant', 'version_tag'), name='uq_learning_release_candidate_version_tag'), models.CheckConstraint(condition=models.Q(('state__in', ['DRAFT', 'CANDIDATE_TAGGED', 'VERIFIED_ON_STAGING', 'PILOT_DEPLOYED', 'ABORTED', 'ROLLED_BACK'])), name='chk_rc_state_valid'), models.CheckConstraint(condition=models.Q(('is_production_target', False)), name='chk_rc_zero_production_deploy')],
            },
        ),
    ]
