# Generated by Django 5.2.17 on 2026-09-14 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models

POSTGRES_P5_RLS_SQL = r"""
DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'learning_pilot_tenant_lifecycle',
        'learning_pilot_prerequisite_checklist',
        'learning_dual_custody_approval_event'
    ];
BEGIN
    IF current_setting('server_version_num', true)::int >= 100000 THEN
        FOREACH tbl IN ARRAY tables LOOP
            EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', tbl);
            EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY;', tbl);
            EXECUTE format('DROP POLICY IF EXISTS p5_tenant_isolation_policy ON %I;', tbl);
            EXECUTE format(
                'CREATE POLICY p5_tenant_isolation_policy ON %I ' ||
                'FOR ALL USING (tenant_id = NULLIF(current_setting(''app.current_tenant'', true), '''')::uuid) ' ||
                'WITH CHECK (tenant_id = NULLIF(current_setting(''app.current_tenant'', true), '''')::uuid);',
                tbl
            );
        END LOOP;

        -- Immutability on dual custody approval and auditability
        EXECUTE 'REVOKE DELETE ON learning_dual_custody_approval_event FROM PUBLIC;';
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'codesho_app') THEN
            EXECUTE 'REVOKE DELETE ON learning_dual_custody_approval_event FROM codesho_app;';
        END IF;
    END IF;
END $$;
"""

REVERSE_P5_RLS_SQL = r"""
DO $$
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'learning_pilot_tenant_lifecycle',
        'learning_pilot_prerequisite_checklist',
        'learning_dual_custody_approval_event'
    ];
BEGIN
    IF current_setting('server_version_num', true)::int >= 100000 THEN
        FOREACH tbl IN ARRAY tables LOOP
            EXECUTE format('DROP POLICY IF EXISTS p5_tenant_isolation_policy ON %I;', tbl);
            EXECUTE format('ALTER TABLE %I NO FORCE ROW LEVEL SECURITY;', tbl);
        END LOOP;
    END IF;
END $$;
"""

def enable_p5_postgres_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        tables = [
            'learning_pilot_tenant_lifecycle',
            'learning_pilot_prerequisite_checklist',
            'learning_dual_custody_approval_event'
        ]
        for tbl in tables:
            cursor.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY;")
            cursor.execute(f"ALTER TABLE {tbl} FORCE ROW LEVEL SECURITY;")
            cursor.execute(f"DROP POLICY IF EXISTS p5_tenant_isolation_policy ON {tbl};")
            cursor.execute(
                f"CREATE POLICY p5_tenant_isolation_policy ON {tbl} "
                f"FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid) "
                f"WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);"
            )
        cursor.execute("REVOKE DELETE ON learning_dual_custody_approval_event FROM PUBLIC;")
        cursor.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'codesho_app') THEN
                REVOKE DELETE ON learning_dual_custody_approval_event FROM codesho_app;
            END IF;
        END $$;
        """)

def disable_p5_postgres_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        tables = [
            'learning_pilot_tenant_lifecycle',
            'learning_pilot_prerequisite_checklist',
            'learning_dual_custody_approval_event'
        ]
        for tbl in tables:
            cursor.execute(f"DROP POLICY IF EXISTS p5_tenant_isolation_policy ON {tbl};")
            cursor.execute(f"ALTER TABLE {tbl} NO FORCE ROW LEVEL SECURITY;")


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0050_p4_pilot_preparation_rls_force'),
        ('platform_tenant', '0004_p3_vs12_guardian_access_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotTenantLifecycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pilot_code', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('ELIGIBILITY_REVIEW', 'Eligibility Review'), ('PREREQUISITES_PENDING', 'Prerequisites Pending'), ('TECHNICALLY_READY', 'Technically Ready'), ('MANAGER_APPROVAL_REQUIRED', 'Manager Approval Required'), ('ACTIVATION_AUTHORIZED', 'Activation Authorized'), ('PILOT_ACTIVE', 'Pilot Active'), ('SUSPENDED', 'Suspended'), ('EXITING', 'Exiting'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32)),
                ('is_synthetic_mode', models.BooleanField(default=True)),
                ('is_production_target', models.BooleanField(default=False)),
                ('initiated_by_id', models.UUIDField()),
                ('technical_reviewer_id', models.UUIDField(blank=True, null=True)),
                ('manager_approver_id', models.UUIDField(blank=True, null=True)),
                ('manager_approval_signed_at', models.DateTimeField(blank=True, null=True)),
                ('activation_token', models.CharField(blank=True, default='', max_length=128)),
                ('suspension_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_lifecycles', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'learning_pilot_tenant_lifecycle',
            },
        ),
        migrations.CreateModel(
            name='PilotPrerequisiteChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_basis_or_consent', models.BooleanField(default=False)),
                ('data_minimization_audited', models.BooleanField(default=False)),
                ('retention_policy_enforced', models.BooleanField(default=False)),
                ('offboarding_policy_verified', models.BooleanField(default=False)),
                ('incident_readiness_tested', models.BooleanField(default=False)),
                ('tenant_authorization_isolated', models.BooleanField(default=False)),
                ('access_review_completed', models.BooleanField(default=False)),
                ('auditability_ledger_active', models.BooleanField(default=False)),
                ('support_readiness_active', models.BooleanField(default=False)),
                ('security_acceptance_cleared', models.BooleanField(default=False)),
                ('manager_authorization_signed', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('certified_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_prerequisites', to='platform_tenant.tenant')),
                ('lifecycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_checklist', to='learning.pilottenantlifecycle')),
            ],
            options={
                'db_table': 'learning_pilot_prerequisite_checklist',
            },
        ),
        migrations.CreateModel(
            name='DualCustodyApprovalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('initiator_id', models.UUIDField()),
                ('secondary_signer_id', models.UUIDField()),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('signature_digest', models.CharField(max_length=128)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dual_custody_approvals', to='platform_tenant.tenant')),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dual_custody_events', to='learning.pilottenantlifecycle')),
            ],
            options={
                'db_table': 'learning_dual_custody_approval_event',
            },
        ),
        migrations.AddIndex(
            model_name='pilottenantlifecycle',
            index=models.Index(fields=['tenant', 'state'], name='idx_pilot_lifecycle_t_state'),
        ),
        migrations.AddConstraint(
            model_name='pilottenantlifecycle',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_pilot_tenant_lifecycle_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='pilottenantlifecycle',
            constraint=models.UniqueConstraint(fields=('tenant', 'pilot_code'), name='uq_learning_pilot_lifecycle_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='pilottenantlifecycle',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['DRAFT', 'ELIGIBILITY_REVIEW', 'PREREQUISITES_PENDING', 'TECHNICALLY_READY', 'MANAGER_APPROVAL_REQUIRED', 'ACTIVATION_AUTHORIZED', 'PILOT_ACTIVE', 'SUSPENDED', 'EXITING', 'CLOSED'])), name='chk_pilot_lifecycle_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='pilottenantlifecycle',
            constraint=models.CheckConstraint(condition=models.Q(('is_production_target', False)), name='chk_pilot_zero_production_target'),
        ),
        migrations.AddConstraint(
            model_name='pilottenantlifecycle',
            constraint=models.CheckConstraint(condition=models.Q(('is_synthetic_mode', True)), name='chk_pilot_synthetic_mode_enforced'),
        ),
        migrations.AddConstraint(
            model_name='pilotprerequisitechecklist',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_pilot_prereq_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='pilotprerequisitechecklist',
            constraint=models.UniqueConstraint(fields=('tenant', 'lifecycle'), name='uq_learning_pilot_prereq_tenant_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='dualcustodyapprovalevent',
            index=models.Index(fields=['tenant', 'action_type'], name='idx_dual_custody_t_action'),
        ),
        migrations.AddIndex(
            model_name='dualcustodyapprovalevent',
            index=models.Index(fields=['nonce'], name='idx_dual_custody_nonce'),
        ),
        migrations.AddConstraint(
            model_name='dualcustodyapprovalevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='uq_learning_dual_custody_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='dualcustodyapprovalevent',
            constraint=models.CheckConstraint(condition=models.Q(('initiator_id', models.F('secondary_signer_id')), _negated=True), name='chk_dual_custody_distinct_signers'),
        ),
        migrations.RunPython(
            code=enable_p5_postgres_rls,
            reverse_code=disable_p5_postgres_rls,
        ),
    ]
