export const authAlphaContent = {
  brand: "CodeSho",
  title: "ورود",
  usernameLabel: "نام کاربری",
  passcodeLabel: "رمز ورود ۶ رقمی",
  submit: "ورود",
  invalidCredentials: "نام کاربری یا رمز ورود صحیح نیست.",
  tooManyAttempts: "تعداد تلاش‌ها زیاد است؛ کمی بعد دوباره امتحان کنید.",
  unavailable: "سرویس ورود موقتاً در دسترس نیست.",
  mustChange: "برای ادامه باید رمز ورودت را تغییر دهی.",
  success: "ورود با موفقیت انجام شد.",
  usernameRequired: "نام کاربری را وارد کنید.",
  passcodeRequired: "رمز ورود را وارد کنید.",
  passcodeInvalid: "رمز ورود باید شش رقم باشد.",
  bootstrapFailed: "ارتباط با سرویس ورود برقرار نشد.",
  retry: "دوباره تلاش کنید.",
  backHome: "بازگشت به صفحه اصلی",
  notFoundTitle: "صفحه مورد نظر پیدا نشد (۴۰۴)",
  notFoundDesc: "آدرسی که وارد کرده‌اید وجود ندارد یا ممکن است منتقل شده باشد.",
  forbiddenTitle: "دسترسی غیرمجاز (۴۰۳)",
  forbiddenDesc: "شما اجازه دسترسی به این بخش را ندارید.",
  sessionExpiredTitle: "نشست کاری شما منقضی شد",
  sessionExpiredDesc: "به دلایل امنیتی لطفاً مجدداً وارد حساب کاربری خود شوید.",
} as const;
