export const studentAlphaContent = {
  brand: "CodeSho",
  shell: {
    drawerCloseLabel: "بستن منوی دانش‌آموز",
    menuButtonLabel: "باز کردن منوی ناوبری",
    navigationLabel: "ناوبری داشبورد دانش‌آموز",
    roleLabel: "دانش‌آموز",
    logoutLabel: "خروج از حساب",
  },
  navigation: [
    { id: "dashboard", label: "داشبورد", href: "/student" },
    { id: "learning", label: "مسیر یادگیری", href: "/student/learning" },
    { id: "coaching", label: "منتورینگ هوشمند", href: "/student/coaching" },
    { id: "growth", label: "رشد و مهارت‌ها", href: "/student/growth" },
    { id: "portfolio", label: "پورتفولیو و پروژه‌ها", href: "/student/portfolio" },
  ],
  dashboard: {
    title: "میز کار و یادگیری دانش‌آموز",
    welcome: "خوش آمدید! مسیر پیشرفت شما فعال و در حال ارزیابی است.",
    currentStateTitle: "وضعیت فعلی یادگیری",
    currentPathName: "توسعه وب و مهندسی هوش مصنوعی (Alpha)",
    currentModule: "مبانی ماژولار فرانت‌اند و اتصال کلاینت",
    progressLabel: "میزان پیشرفت مسیر فعال",
    progressValue: 68,
    nextActionTitle: "اقدام پیشنهادی بعدی",
    nextActionDesc: "تکمیل چالش تعاملی BiDi و استقرار کامپوننت‌های بهینه‌شده",
    nextActionButton: "ادامه یادگیری چالش",
    activeLearningTitle: "فعالیت‌های جاری",
    guidanceTitle: "توصیه منتور هوشمند",
    guidanceText: "پیشرفت شما در مفاهیم پایه‌ای ساختاریافته است. گام بعدی تمرکز بر هندلینگ وضعیت‌های خالی و خطا در لایه کاربر است.",
  },
  indicators: {
    check: "✓",
    bullet: "●",
    step1: "۱",
    step2: "۲",
  },
  learning: {
    title: "مسیرهای یادگیری ساختاریافته",
    description: "نمای گام‌به‌گام ماژول‌ها، تکالیف عملی و وضعیت‌های فعال.",
    currentPath: "مسیر جامع فرانت‌اند و هوش مصنوعی",
    module1Title: "۱. مبانی طراحی سیستم و توکن‌ها",
    module1Status: "تکمیل شده",
    module2Title: "۲. معماری کلاینت و احراز هویت",
    module2Status: "در حال انجام",
    module3Title: "۳. مدیریت داده و شبیه‌سازی ران‌تایم",
    module3Status: "قفل شده تا تکمیل ماژول قبلی",
    actionContinue: "ادامه ماژول جاری",
  },
  coaching: {
    title: "هدایت و مربیگری هوشمند (Coaching)",
    description: "پشتیبانی ساختاریافته و راهنمایی‌های تحلیلی بر پایه پیشرفت اختصاصی دانش‌آموز.",
    sourceLabel: "سیستم منتورینگ هوشمند CodeSho (شبیه‌سازی تحلیلی)",
    adviceTitle: "تحلیل عملکرد اخیر",
    adviceText: "هیچ بن‌بستی در تعاملات ثبت نشده است. ساختار کدهای شما منطبق با استانداردهای کیفیت رابط کاربری است.",
    actionPrompt: "ثبت پرسش از منتور",
  },
  growth: {
    title: "رشد فردی و ارزیابی مهارت‌ها",
    description: "نمایش دستاوردها، اهداف یادگیری و تکامل فردی (بدون رتبه‌بندی رقابتی و با تمرکز بر پیشرفت شخصی).",
    skillsTitle: "مهارت‌های کسب‌شده",
    skill1: "معماری کامپوننت‌های دسترس‌پذیر",
    skill2: "پیاده‌سازی امن احراز هویت",
    skill3: "سازگاری BiDi/RTL",
    milestoneTitle: "نقاط عطف پیش رو",
    milestone1: "پیاده‌سازی کامل استیت‌های خطای ۴۰۳ و ۴۰۱",
    milestone2: "ارزیابی نهایی خروجی ران‌تایم",
  },
  portfolio: {
    title: "پورتفولیو و نمونه‌کارهای فردی",
    description: "مجموعه پروژه‌های تکمیل‌شده در محیط آزمون و توسعه شخصی.",
    privacyNote: "تمامی پروژه‌ها در محیط ایزوله تننت قرار دارند و اشتراک‌گذاری عمومی بدون تأیید سرپرست قفل است.",
    project1Title: "پیاده‌سازی شل ران‌تایم فرانت‌اند",
    project1Status: "بررسی‌شده و معتبر",
    actionView: "مشاهده جزئیات پروژه",
    actionAdd: "ثبت پروژه جدید",
  },
  states: {
    emptyTitle: "موردی برای نمایش وجود ندارد",
    emptyDesc: "هیچ داده‌ای در این بخش ثبت نشده است. می‌توانید با شروع فعالیت جدید اقدام کنید.",
    loadingTitle: "در حال دریافت اطلاعات...",
    errorTitle: "خطا در برقراری ارتباط",
    errorDesc: "پاسخ معتبری از سرور دریافت نشد. لطفاً دوباره تلاش کنید.",
    retryButton: "تلاش مجدد",
  },
} as const;
