export const studentAlphaContent = {
  brand: "CodeSho",
  tagline: "مسیر بهتر، آینده روشن‌تر",
  shell: {
    drawerCloseLabel: "بستن منوی دانش‌آموز",
    menuButtonLabel: "باز کردن منوی ناوبری",
    navigationLabel: "ناوبری داشبورد دانش‌آموز",
    roleLabel: "دانش‌آموز",
    userName: "علی محمدی (سنتتیک)",
    logoutLabel: "خروج از حساب",
    searchPlaceholder: "جستجوی آموزش‌ها، پروژه‌ها، مطالب و ...",
    searchShortcut: "Ctrl + K",
    notificationsLabel: "اعلان‌ها",
    unreadCount: "۲",
    settingsLabel: "تنظیمات",
    supportLabel: "پشتیبانی",
    sidebarPromoTitle: "رویاهات را با کدنویسی بساز",
    sidebarPromoSubtitle: "ما در کنارتیم",
    sidebarPromoButton: "شروع مسیر یادگیری",
  },
  navigation: [
    { id: "dashboard", label: "داشبورد", href: "/student" },
    { id: "learning", label: "مسیر یادگیری", href: "/student/learning" },
    { id: "coaching", label: "منتورینگ هوشمند", href: "/student/coaching" },
    { id: "growth", label: "رشد و مهارت‌ها", href: "/student/growth" },
    { id: "portfolio", label: "پورتفولیو و پروژه‌ها", href: "/student/portfolio" },
  ],
  dashboard: {
    title: "میز کار و یادگیری دانش‌آموز",
    welcome: "سلام علی جان! با قدرت به مسیرت ادامه بده!",
    welcomeSubtitle: "هوش مصنوعی CodeSho همیشه کنار توست تا سریع‌تر یاد بگیری، بهتر رشد کنی و به هدف‌هایت برسی.",
    heroBadge: "آینده روشن",
    heroQuote: "«هر خط کد، یک قدم به نسخه بهتر توست»",
    heroBrandTag: "CodeSho — More Skills, A Brighter Tomorrow",
    askMentorAction: "ثبت پرسش از منتور",
    personalPlanAction: "دریافت برنامه اختصاصی من",

    // 4 KPI Cards
    kpi1Title: "پیشرفت کل دوره‌ها",
    kpi1Value: "۶۸٪",
    kpi1Sub: "+۱۲٪ نسبت به ماه قبل",

    kpi2Title: "تکالیف تکمیل شده",
    kpi2Value: "۲۴",
    kpi2Sub: "+۵ در هفته اخیر",

    kpi3Title: "روزهای مطالعه متوالی",
    kpi3Value: "۱۲ روز",
    kpi3Sub: "رکورد شخصی پایدار",

    kpi4Title: "امتیاز از منتورها",
    kpi4Value: "۴.۸ از ۵",
    kpi4Sub: "+۰.۳ نسبت به ماه قبل",

    // Performance Chart Section
    chartTitle: "عملکرد یادگیری در هفته‌های اخیر",
    chartPeriod: "۴ هفته اخیر",
    chartTodayBadge: "امروز",
    chartTodayStat: "۸۵٪ (+۲۰٪ نسبت به هفته قبل)",
    chartW1: "۲۳ مرداد",
    chartW2: "۳۰ مرداد",
    chartW3: "۶ شهریور",
    chartW4: "۱۳ شهریور",
    chartW5: "۲۰ شهریور",
    chartW6: "امروز",

    // Learning Goal Section
    goalTitle: "هدف یادگیری شما",
    goalFilter: "دوره فعلی",
    goalValue: "۶۸٪",
    goalStatus: "تکمیل شده",
    goalCourseName: "توسعه‌دهنده فرانت‌اند",
    goalModulesCompleted: "از ۱۲ ماژول، ۸ ماژول تکمیل شده",

    // Skill Growth Section
    skillsTitle: "رشد مهارت‌ها",
    skillsViewAll: "مشاهده همه",
    skill1Name: "HTML & CSS",
    skill1Val: "۹۰٪",
    skill2Name: "JavaScript",
    skill2Val: "۷۵٪",
    skill3Name: "React",
    skill3Val: "۶۰٪",
    skill4Name: "Git & GitHub",
    skill4Val: "۵۵٪",
    skill5Name: "Problem Solving",
    skill5Val: "۷۰٪",

    // Recent Activities
    recentTitle: "فعالیت‌های اخیر",
    recentViewAll: "مشاهده همه",
    act1Desc: "درس «مفهوم State در React» را تکمیل کردید",
    act1Time: "۲ ساعت پیش",
    act2Desc: "پروژه «Todo App» ارسال شد",
    act2Time: "۱ روز پیش",
    act3Desc: "پاسخ جدید از منتور شما: «کارت عالیه! فقط روی مدیریت state بیشتر کار کن.»",
    act3Time: "۲ روز پیش",

    // Smart Recommendations
    recsTitle: "پیشنهادهای هوشمند برای شما",
    recsBadge: "بر اساس مسیر شما",
    rec1Title: "درس بعدی: مدیریت State در React",
    rec1Time: "۱۵ دقیقه",
    rec2Title: "پروژه پیشنهادی: ساخت یک وب‌اپلیکیشن هواشناسی",
    rec2Level: "متوسط",
    rec3Title: "جلسه منتورینگ: رزرو جلسه با منتور برای بررسی پروژه",
    rec3Action: "رزرو جلسه",

    // Milestone / Success Summary
    milestoneBannerTitle: "تو در مسیر درستی هستی!",
    milestoneBannerDesc: "با استمرار، به اهداف بزرگ‌تری می‌رسی.",
    step1: "یادگیری مهارت‌ها",
    step2: "ساخت پروژه‌ها",
    step3: "دریافت بازخورد",
    step4: "فرصت‌های شغلی",
    milestoneFooter: "«موفقیت حاصل قدم‌های کوچک و پیوسته است»",

    // Existing semantics
    currentStateTitle: "وضعیت فعلی یادگیری",
    currentPathName: "توسعه وب و مهندسی هوش مصنوعی (Alpha)",
    currentModule: "مبانی ماژولار فرانت‌اند و اتصال کلاینت",
    progressLabel: "میزان پیشرفت مسیر فعال",
    progressValue: 68,
    nextActionTitle: "اقدام پیشنهادی بعدی",
    nextActionDesc: "تکمیل چالش تعاملی BiDi و استقرار کامپوننت‌های بهینه‌شده",
    nextActionButton: "ادامه یادگیری چالش",
    activeLearningTitle: "فعالیت‌های جاری",
    guidanceTitle: "توصیه منتور هوشمند",
    guidanceText: "پیشرفت شما در مفاهیم پایه‌ای ساختاریافته است. گام بعدی تمرکز بر هندلینگ وضعیت‌های خالی و خطا در لایه کاربر است.",
  },
  icons: {
    brandCode: "</>",
    search: "🔍",
    bell: "🔔",
    settings: "⚙️",
    support: "🎧",
    sparkles: "✨",
    calendar: "📅",
    arrowUp: "↑",
    graduate: "🎓",
    document: "📝",
    fire: "🔥",
    star: "⭐",
    chart: "📊",
    target: "🎯",
    trending: "📈",
    clock: "🕒",
    file: "📄",
    chat: "💬",
    trophy: "🏆",
    map: "🗺️",
    lightbulb: "💡",
    question: "❓",
    history: "📜",
    laptop: "💻",
    gear: "⚙️",
    flag: "🏁",
  },
  indicators: {
    check: "✓",
    bullet: "●",
    step1: "۱",
    step2: "۲",
  },
  commonLabels: {
    activeProjectsBadge: "۴ پروژه فعال",
    activeShowcaseTitle: "ویترین پروژه‌ها و نمونه‌کارهای فعال",
    quotePortfolio: "«کیفیت پروژه‌ها هویت حرفه‌ای شما در بازار است»",
    quoteLearning: "«هر مبحث عمیق، پایه‌گذار کدهای مطمئن در آینده است»",
    quoteCoaching: "«پشتیبانی دقیق و مستمر، ضامن عبور از چالش‌های فنی است»",
    quoteGrowth: "«مقایسه تنها با گذشته خود، مسیر پایدار پیشرفت است»",
    progress100: "۱۰۰٪ تکمیل",
    progress65: "۶۵٪ تکمیل",
    pendingModule2: "در انتظار آزمون ماژول ۲",
    complementaryPhase: "فاز تکمیلی",
    refStandard: "استاندارد مرجع",
    officialGuide: "راهنمای رسمی",
    safetyRules: "الزامات ایمنی",
    learningGuideSub: "راهنمایی در مسیر یادگیری",
    verifiedAnalysis: "تحلیل معتبر",
    analyticSuggestion: "پیشنهاد تحلیلی",
    askQuestionBtn: "طرح پرسش",
    viewRelatedModule: "مشاهده سرفصل مرتبط",
    personalContinuity: "استمرار فردی",
    establishedRecords: "سوابق تثبیت‌شده",
    step1Growth: "گام اول رشد",
    step2Growth: "گام دوم رشد",
    step3Growth: "گام سوم رشد",
    nearGoal: "هدف نزدیک",
    midGoal: "هدف میان‌مدت",
    proShowcase: "ارائه حرفه‌ای",
    viewPortfolioLink: "مشاهده پورتفولیو",
    mentorAvatarInitial: "م",
    fastResponseBadge: "پاسخگویی سریع",
    architectureAnalysisBadge: "تحلیل معماری",
    noRankingBadge: "عدم رتبه‌بندی",
    personalContinuityBadge: "استمرار شخصی",
    ariaPortfolioShowcase: "ویترین پروژه‌های دانش‌آموز",
    ariaPortfolioAnalytics: "تحلیل تکمیلی پورتفولیو",
    ariaLearningRoadmap: "نقشه راه تفصیلی ماژول‌ها",
    ariaLearningResources: "منابع و ارتباطات یادگیری",
    ariaCoachingQuestions: "مشاوره و پرسش‌های کلیدی",
    ariaCoachingHistory: "تاریخچه بازخوردهای منتورینگ",
    ariaGrowthSkills: "تحلیل مهارت‌ها و نقاط عطف",
    ariaGrowthRoadmap: "نقشه تعمیق رشد",
  },
  learning: {
    title: "مسیرهای یادگیری ساختاریافته",
    description: "نقشه راه مرحله‌به‌مرحله پودمان‌ها، چالش‌های عملی، زمان تخمینی و وضعیت ماژول‌ها.",
    currentPath: "مسیر جامع فرانت‌اند و مهندسی هوش مصنوعی",
    heroBadge: "برنامه آموزشی فعال",
    heroActionPrimary: "ادامه یادگیری فعال",
    heroActionSecondary: "مشاهده کاتالوگ دوره‌ها",
    kpi1Title: "پیشرفت کل سرفصل‌ها",
    kpi1Value: "۶۸٪",
    kpi1Sub: "۸ از ۱۲ ماژول",
    kpi2Title: "ساعات تمرین و کدنویسی",
    kpi2Value: "۵۴ ساعت",
    kpi2Sub: "۱۲ ساعت در این هفته",
    kpi3Title: "تکالیف کدنویسی تاییدشده",
    kpi3Value: "۱۶ پروژه",
    kpi3Sub: "۱۰۰٪ تاییدیه کیفیت",
    kpi4Title: "شاخص استمرار پودمان‌ها",
    kpi4Value: "۹۴٪",
    kpi4Sub: "سطح تسلط عالی",
    module1Title: "۱. مبانی طراحی سیستم، توکن‌ها و استاندارد BiDi",
    module1Status: "تکمیل شده",
    module1Time: "۱۲ ساعت مطالعه و تمرین",
    module1Desc: "آشنایی با اصول پایه‌ای طراحی سیستم، پالت‌های دسترسی‌پذیر و استانداردهای چیدمان راست‌به‌چپ.",
    module2Title: "۲. معماری کلاینت، احراز هویت و مدیریت جلسات",
    module2Status: "در حال انجام",
    module2Time: "۱۸ ساعت (۶ ساعت باقی‌مانده)",
    module2Desc: "پیاده‌سازی امن احراز هویت مبتنی بر کوکی، توکن‌های ضد جعل CSRF و ایزولاسیون کامل نشست.",
    module3Title: "۳. مدیریت داده، هوش مصنوعی تحلیلی و شبیه‌سازی ران‌تایم",
    module3Status: "قفل شده تا تکمیل ماژول قبلی",
    module3Time: "۲۴ ساعت تخمینی",
    module3Desc: "توسعه کلاینت‌های تحلیلی، ساختاردهی به جریان‌های داده‌ای و ارتباط امن با مدل‌های زبانی.",
    module4Title: "۴. تست‌های جامع امنیتی و استقرار کانتینری",
    module4Status: "برنامه آتی",
    module4Time: "۱۶ ساعت تخمینی",
    module4Desc: "پیاده‌سازی تست‌های نفوذ چندمستأجری، گیت‌های کنترل کیفی و پکیج‌بندی داکر.",
    actionContinue: "ادامه ماژول جاری",
    actionDetails: "مشاهده سرفصل‌ها",
    roadmapHeader: "نقشه راه تفصیلی ماژول‌ها",
    progressRatio: "۸ از ۱۲ ماژول گذرانده شده",
    analyticsTitle: "تحلیل پیشرفت هفتگی یادگیری",
    analyticsSub: "روند مطالعه و تمرین در هفته‌های جاری",
    prerequisitesTitle: "پیش‌نیازها و منابع تکمیلی",
    prereq1: "مستندات استاندارد W3C برای Accessibility",
    prereq2: "راهنمای معماری لایه‌ای Next.js App Router",
    prereq3: "مجموعه قواعد امنیتی OWASP Top 10",
  },
  coaching: {
    title: "هدایت و مربیگری هوشمند (Coaching)",
    description: "پشتیبانی ساختاریافته، تاریخچه راهنمایی‌ها و تحلیل اختصاصی بدون شبیه‌سازی فریبنده انسان.",
    sourceLabel: "سیستم منتورینگ هوشمند CodeSho (شبیه‌سازی تحلیلی)",
    heroBadge: "دستیار تحلیلی کدنویسی فعال",
    heroActionPrimary: "ثبت پرسش تحلیلی جدید",
    heroActionSecondary: "رزرو جلسه رفع اشکال",
    kpi1Title: "جلسات مشاوره و منتورینگ",
    kpi1Value: "۱۲ جلسه",
    kpi1Sub: "۳ جلسه در ماه جاری",
    kpi2Title: "پرسش‌های رفع ابهام شده",
    kpi2Value: "۲۸ سوال",
    kpi2Sub: "پاسخ ساختاریافته",
    kpi3Title: "میانگین رضایت از بازخورد",
    kpi3Value: "۴.۹ از ۵",
    kpi3Sub: "بر مبنای بازخورد شما",
    kpi4Title: "نرخ پیشرفت پس از مشاوره",
    kpi4Value: "+۳۵٪",
    kpi4Sub: "سرعت حل مسائل",
    adviceTitle: "تحلیل عملکرد و راهنمایی تحلیلی اخیر",
    adviceText: "هیچ بن‌بستی در تعاملات اخیر شما ثبت نشده است. ساختار کدهای شما منطبق با استانداردهای کیفیت رابط کاربری و اصول تمیز است.",
    actionPrompt: "ثبت پرسش جدید از دستیار منتور",
    recommendedQuestionsTitle: "پرسش‌های پیشنهادی گام بعدی",
    q1: "چگونه ساختار State در فرم‌های چندمرحله‌ای را بهینه کنم؟",
    q2: "بهترین الگو برای تست‌های منفی دسترسی چندمستأجری چیست؟",
    q3: "روش استاندارد پیاده‌سازی تمرکز کیبورد در منوهای کشویی چیست؟",
    historyTitle: "تاریخچه بازخوردهای اخیر منتورینگ",
    h1Date: "۲ روز پیش",
    h1Title: "بررسی کامپوننت دکمه و دسترس‌پذیری",
    h1Content: "ساختار دسترس‌پذیری عالی است، لطفاً به تضاد رنگ در حالت فوکوس کیبورد بیشتر دقت کنید.",
    h2Date: "۵ روز پیش",
    h2Title: "معماری روت‌های کلاینت در Next.js",
    h2Content: "الگوی بارگذاری موازی صفحات برای بهبود First Contentful Paint به خوبی اجرا شده است.",
    h3Date: "۱ هفته پیش",
    h3Title: "پایداری استیت‌ها در خطاهای شبکه",
    h3Content: "پیاده‌سازی حالت‌های Retry و نمایش پیام‌های خطای راهنما کاملاً با استانداردهای UI همخوان است.",
    actionViewHistory: "مشاهده متن کامل گفتگو",
    mentorCardTitle: "منتور اختصاصی شما",
    mentorName: "مهندس سهراب رحیمی",
    mentorRole: "معمار ارشد فرانت‌اند و مربی تخصصی",
    mentorStatus: "پاسخگو ظرف حداکثر ۲ ساعت",
  },
  growth: {
    title: "رشد فردی و ارزیابی مهارت‌ها",
    description: "نمایش دستاوردها، اهداف یادگیری و تکامل فردی (۱۰۰٪ بدون رتبه‌بندی رقابتی، لیدربورد یا مقایسه با همسالان).",
    invariantBadge: "عدم رتبه‌بندی و مقایسه فردی فعال",
    heroBadge: "شاخص‌های تکامل و مهارت فردی",
    heroActionPrimary: "تعریف هدف یادگیری جدید",
    heroActionSecondary: "دریافت کارنامه تحلیلی رشد",
    kpi1Title: "شاخص تسلط جامع مهارت‌ها",
    kpi1Value: "۸۸٪",
    kpi1Sub: "+۱۲٪ در ماه گذشته",
    kpi2Title: "مفاهیم تخصصی آموخته‌شده",
    kpi2Value: "۴۲ مفهوم",
    kpi2Sub: "بر مبنای استانداردهای روز",
    kpi3Title: "نقاط عطف محقق‌شده",
    kpi3Value: "۹ دستاورد",
    kpi3Sub: "بدون وقفه در برنامه",
    kpi4Title: "ساعت تمرین مستقل عمیق",
    kpi4Value: "۷۶ ساعت",
    kpi4Sub: "تمرکز بالای یادگیری",
    skillsTitle: "شاخص‌های رشد و تسلط مهارتی فردی",
    skill1: "معماری کامپوننت‌های دسترس‌پذیر",
    skill1Rate: "۹۰٪ تسلط فردی",
    skill2: "پیاده‌سازی امن احراز هویت و سشن‌ها",
    skill2Rate: "۸۵٪ تسلط فردی",
    skill3: "سازگاری BiDi/RTL و جلوگیری از سرریز",
    skill3Rate: "۹۲٪ تسلط فردی",
    skill4: "مدیریت فرم‌ها و اعتبارسنجی داده‌ها",
    skill4Rate: "۸۸٪ تسلط فردی",
    skill5: "یکپارچه‌سازی تست‌های کلاینت و سرور",
    skill5Rate: "۸۲٪ تسلط فردی",
    milestoneTitle: "نقاط عطف مهارتی پایدار",
    milestone1: "پیاده‌سازی کامل استیت‌های خطای ۴۰۳ و ۴۰۱ با هدایت دقیق کاربر",
    milestone1Date: "کسب شده در ۱۵ شهریور",
    milestone2: "ارزیابی نهایی خروجی ران‌تایم و پاس کردن ۱۰ گیت سیستمی",
    milestone2Date: "هدف پیش رو (در حال ارزیابی)",
    milestone3: "طراحی سیستم توکن‌های رنگی و تایپوگرافی بدون متغیرهای هاردکد",
    milestone3Date: "کسب شده در ۲۸ مرداد",
    selfSummaryTitle: "خلاصه روند تکامل شخصی",
    selfSummaryText: "شما با استمرار روزانه توانسته‌اید نرخ تسلط خود را در ۲ هفته گذشته به میزان ۱۸٪ افزایش دهید.",
    growthPlanTitle: "برنامه پیشنهادی تعمیق مهارت‌ها",
    planStep1: "تکمیل ماژول پیشرفته کشف خطاها در فرم‌های ورود",
    planStep2: "اجرای تست‌های اتوماتیک در مرورگر زنده با ابزارهای استاندارد",
    planStep3: "ارائه نمونه‌کار در قالب پورتفولیوی شخصی به منتور",
  },
  portfolio: {
    title: "پورتفولیو و ویترین پروژه‌های فردی",
    description: "مجموعه پروژه‌های تکمیل‌شده در محیط آزمون و توسعه شخصی با رعایت کامل تفکیک حریم خصوصی.",
    heroBadge: "ویترین حرفه‌ای نمونه‌کارها",
    heroActionPrimary: "ثبت پروژه جدید در پورتفولیو",
    heroActionSecondary: "دریافت خروجی رزومه استاندارد",
    privacyNote: "تمامی پروژه‌ها در محیط ایزوله تننت (alpha-synth) قرار دارند و هرگونه اشتراک‌گذاری عمومی مشروط به تأیید کاربر و سرپرست است.",
    privacyBadge: "حریم خصوصی ایزوله (Tenant Scoped)",
    kpi1Title: "پروژه‌های تکمیل‌شده",
    kpi1Value: "۶ پروژه",
    kpi1Sub: "+۲ در این ترم",
    kpi2Title: "در صف بررسی منتور",
    kpi2Value: "۲ مورد",
    kpi2Sub: "زمان پاسخ کمتر از ۲۴ ساعت",
    kpi3Title: "مستندات و خروجی تاییدشده",
    kpi3Value: "۱۴ سند",
    kpi3Sub: "استاندارد کیفی A+",
    kpi4Title: "شاخص آمادگی بازار کار",
    kpi4Value: "۸۶٪",
    kpi4Sub: "سطح Junior Ready",
    project1Title: "پیاده‌سازی شل ران‌تایم فرانت‌اند و سیستم ناوبری BiDi",
    project1Status: "بررسی‌شده و معتبر",
    project1Tags: "React • TypeScript • CSS Modules",
    project1Desc: "سیستم کامل ناوبری دسکتاپ و موبایل با پشتیبانی از چیدمان راست‌به‌چپ، تم‌های چندگانه و دسترس‌پذیری WCAG.",
    project1Metrics: "۱۰۰٪ پوشش استانداردهای UI",
    project2Title: "پروژه ماشین حساب ماژولار با تست‌های ایزوله",
    project2Status: "در صف بازبینی منتور",
    project2Tags: "Python • Docker • Architecture",
    project2Desc: "طراحی ماژول محاسباتی با رعایت الگوهای SOLID، داکرایز شده با تست‌های یکپارچگی مستقل.",
    project2Metrics: "۲۴ تست منفی و مثبت پاس‌شده",
    project3Title: "داشبورد تحلیلی و مانیتورینگ عملکرد دانش‌آموز",
    project3Status: "تکمیل شده و مستند",
    project3Tags: "Next.js • Charting • Accessibility",
    project3Desc: "نمایش گراف‌های پیشرفت بدون ایجاد حس رقابت مخرب و پایبندی به اصول استمرار شخصی.",
    project3Metrics: "امتیاز عملکرد ۹۸ از ۱۰۰",
    project4Title: "سرویس مدیریت نشست‌ها و احراز هویت دو مرحله‌ای",
    project4Status: "در حال بهینه‌سازی نهایی",
    project4Tags: "Security • Auth • Sessions",
    project4Desc: "پیاده‌سازی چرخه کامل لاگین و بازیابی رمز عبور با اعتبارسنجی امنیتی سخت‌گیرانه.",
    project4Metrics: "سازگار با دستورالعمل‌های امنیتی",
    actionView: "مشاهده جزئیات پروژه",
    actionEdit: "ویرایش مستندات",
    actionAdd: "ثبت پروژه جدید در پورتفولیو",
    recentSubmissionsTitle: "آخرین ارسال‌ها و مستندات پروژه",
    sub1Title: "بارگذاری مستندات معماری پروژه شل فرانت‌اند",
    sub1Time: "دیروز در ساعت ۱۸:۳۰",
    sub2Title: "ثبت گزارش ارزیابی کیفی کد ماشین‌حساب پایتون",
    sub2Time: "۳ روز پیش",
    feedbackSummaryTitle: "خلاصه ارزیابی‌های کیفی منتورها",
    feedback1: "«ساختار کامپوننت‌ها و نام‌گذاری متغیرها کاملاً خوانا و مطابق الگوهای صنعتی است.»",
    feedback2: "«توجه به استانداردهای دسترس‌پذیری در ویجت‌ها ارزش پورتفولیو را به شکل چشم‌گیری ارتقا داده است.»",
    readinessTitle: "ارزیابی آمادگی برای ارائه به کارفرما",
    readinessScore: "۸۶٪ آمادگی کامل",
    readinessDetail: "شما نیازمند افزودن تنها ۱ پروژه فول‌استک دیگر برای رسیدن به سطح ارشدیت هستید.",
  },
  states: {
    emptyTitle: "موردی برای نمایش وجود ندارد",
    emptyDesc: "هیچ داده‌ای در این بخش ثبت نشده است. می‌توانید با شروع فعالیت جدید اقدام کنید.",
    loadingTitle: "در حال دریافت اطلاعات...",
    errorTitle: "خطا در برقراری ارتباط",
    errorDesc: "پاسخ معتبری از سرور دریافت نشد. لطفاً دوباره تلاش کنید.",
    retryButton: "تلاش مجدد",
  },
} as const;
