export const studentAlphaContent = {
  brand: "CodeSho",
  tagline: "مسیر بهتر، آینده روشن‌تر",
  shell: {
    drawerCloseLabel: "بستن منوی دانش‌آموز",
    menuButtonLabel: "باز کردن منوی ناوبری",
    navigationLabel: "ناوبری داشبورد دانش‌آموز",
    roleLabel: "دانش‌آموز",
    userName: "علی محمدی (سنتتیک)",
    logoutLabel: "خروج از حساب",
    searchPlaceholder: "جستجوی آموزش‌ها، پروژه‌ها، مطالب و ...",
    searchShortcut: "Ctrl + K",
    notificationsLabel: "اعلان‌ها",
    unreadCount: "۲",
    settingsLabel: "تنظیمات",
    supportLabel: "پشتیبانی",
    sidebarPromoTitle: "رویاهات را با کدنویسی بساز",
    sidebarPromoSubtitle: "ما در کنارتیم",
    sidebarPromoButton: "شروع مسیر یادگیری",
  },
  navigation: [
    { id: "dashboard", label: "داشبورد", href: "/student" },
    { id: "learning", label: "مسیر یادگیری", href: "/student/learning" },
    { id: "coaching", label: "منتورینگ هوشمند", href: "/student/coaching" },
    { id: "growth", label: "رشد و مهارت‌ها", href: "/student/growth" },
    { id: "portfolio", label: "پورتفولیو و پروژه‌ها", href: "/student/portfolio" },
  ],
  dashboard: {
    title: "میز کار و یادگیری دانش‌آموز",
    welcome: "سلام علی جان! با قدرت به مسیرت ادامه بده!",
    welcomeSubtitle: "هوش مصنوعی CodeSho همیشه کنار توست تا سریع‌تر یاد بگیری، بهتر رشد کنی و به هدف‌هایت برسی.",
    heroBadge: "آینده روشن",
    heroQuote: "«هر خط کد، یک قدم به نسخه بهتر توست»",
    heroBrandTag: "CodeSho — More Skills, A Brighter Tomorrow",
    askMentorAction: "ثبت پرسش از منتور",
    personalPlanAction: "دریافت برنامه اختصاصی من",

    // 4 KPI Cards
    kpi1Title: "پیشرفت کل دوره‌ها",
    kpi1Value: "۶۸٪",
    kpi1Sub: "+۱۲٪ نسبت به ماه قبل",

    kpi2Title: "تکالیف تکمیل شده",
    kpi2Value: "۲۴",
    kpi2Sub: "+۵ در هفته اخیر",

    kpi3Title: "روزهای مطالعه متوالی",
    kpi3Value: "۱۲ روز",
    kpi3Sub: "رکورد شخصی! 🔥",

    kpi4Title: "امتیاز از منتورها",
    kpi4Value: "۴.۸ از ۵",
    kpi4Sub: "+۰.۳ نسبت به ماه قبل",

    // Performance Chart Section
    chartTitle: "عملکرد یادگیری در هفته‌های اخیر",
    chartPeriod: "۴ هفته اخیر",
    chartTodayBadge: "امروز",
    chartTodayStat: "۸۵٪ (+۲۰٪ نسبت به هفته قبل)",
    chartW1: "۲۳ مرداد",
    chartW2: "۳۰ مرداد",
    chartW3: "۶ شهریور",
    chartW4: "۱۳ شهریور",
    chartW5: "۲۰ شهریور",
    chartW6: "امروز",

    // Learning Goal Section
    goalTitle: "هدف یادگیری شما",
    goalFilter: "دوره فعلی",
    goalValue: "۶۸٪",
    goalStatus: "تکمیل شده",
    goalCourseName: "توسعه‌دهنده فرانت‌اند",
    goalModulesCompleted: "از ۱۲ ماژول، ۸ ماژول تکمیل شده",

    // Skill Growth Section
    skillsTitle: "رشد مهارت‌ها",
    skillsViewAll: "مشاهده همه",
    skill1Name: "HTML & CSS",
    skill1Val: "۹۰٪",
    skill2Name: "JavaScript",
    skill2Val: "۷۵٪",
    skill3Name: "React",
    skill3Val: "۶۰٪",
    skill4Name: "Git & GitHub",
    skill4Val: "۵۵٪",
    skill5Name: "Problem Solving",
    skill5Val: "۷۰٪",

    // Recent Activities
    recentTitle: "فعالیت‌های اخیر",
    recentViewAll: "مشاهده همه",
    act1Desc: "درس «مفهوم State در React» را تکمیل کردید",
    act1Time: "۲ ساعت پیش",
    act2Desc: "پروژه «Todo App» ارسال شد",
    act2Time: "۱ روز پیش",
    act3Desc: "پاسخ جدید از منتور شما: «کارت عالیه! فقط روی مدیریت state بیشتر کار کن.»",
    act3Time: "۲ روز پیش",

    // Smart Recommendations
    recsTitle: "پیشنهادهای هوشمند برای شما",
    recsBadge: "بر اساس مسیر شما",
    rec1Title: "درس بعدی: مدیریت State در React",
    rec1Time: "۱۵ دقیقه",
    rec2Title: "پروژه پیشنهادی: ساخت یک وب‌اپلیکیشن هواشناسی",
    rec2Level: "متوسط",
    rec3Title: "جلسه منتورینگ: رزرو جلسه با منتور برای بررسی پروژه",
    rec3Action: "رزرو جلسه",

    // Milestone / Success Summary
    milestoneBannerTitle: "تو در مسیر درستی هستی!",
    milestoneBannerDesc: "با استمرار، به اهداف بزرگ‌تری می‌رسی.",
    step1: "یادگیری مهارت‌ها",
    step2: "ساخت پروژه‌ها",
    step3: "دریافت بازخورد",
    step4: "فرصت‌های شغلی",
    milestoneFooter: "«موفقیت حاصل قدم‌های کوچک و پیوسته است»",

    // Existing semantics
    currentStateTitle: "وضعیت فعلی یادگیری",
    currentPathName: "توسعه وب و مهندسی هوش مصنوعی (Alpha)",
    currentModule: "مبانی ماژولار فرانت‌اند و اتصال کلاینت",
    progressLabel: "میزان پیشرفت مسیر فعال",
    progressValue: 68,
    nextActionTitle: "اقدام پیشنهادی بعدی",
    nextActionDesc: "تکمیل چالش تعاملی BiDi و استقرار کامپوننت‌های بهینه‌شده",
    nextActionButton: "ادامه یادگیری چالش",
    activeLearningTitle: "فعالیت‌های جاری",
    guidanceTitle: "توصیه منتور هوشمند",
    guidanceText: "پیشرفت شما در مفاهیم پایه‌ای ساختاریافته است. گام بعدی تمرکز بر هندلینگ وضعیت‌های خالی و خطا در لایه کاربر است.",
  },
  icons: {
    brandCode: "</>",
    search: "🔍",
    bell: "🔔",
    settings: "⚙️",
    support: "🎧",
    sparkles: "✨",
    calendar: "📅",
    arrowUp: "↑",
    graduate: "🎓",
    document: "📝",
    fire: "🔥",
    star: "⭐",
    chart: "📊",
    target: "🎯",
    trending: "📈",
    clock: "🕒",
    file: "📄",
    chat: "💬",
    trophy: "🏆",
    map: "🗺️",
    lightbulb: "💡",
    question: "❓",
    history: "📜",
    laptop: "💻",
    gear: "⚙️",
    flag: "🏁",
  },
  indicators: {
    check: "✓",
    bullet: "●",
    step1: "۱",
    step2: "۲",
  },
  learning: {
    title: "مسیرهای یادگیری ساختاریافته",
    description: "نقشه راه مرحله‌به‌مرحله پودمان‌ها، چالش‌های عملی، زمان تخمینی و وضعیت ماژول‌ها.",
    currentPath: "مسیر جامع فرانت‌اند و مهندسی هوش مصنوعی",
    module1Title: "۱. مبانی طراحی سیستم، توکن‌ها و استاندارد BiDi",
    module1Status: "تکمیل شده",
    module1Time: "۱۲ ساعت مطالعه و تمرین",
    module2Title: "۲. معماری کلاینت، احراز هویت و مدیریت جلسات",
    module2Status: "در حال انجام",
    module2Time: "۱۸ ساعت (۶ ساعت باقی‌مانده)",
    module3Title: "۳. مدیریت داده، هوش مصنوعی تحلیلی و شبیه‌سازی ران‌تایم",
    module3Status: "قفل شده تا تکمیل ماژول قبلی",
    module3Time: "۲۴ ساعت تخمینی",
    actionContinue: "ادامه ماژول جاری",
    roadmapHeader: "نقشه راه تفصیلی ماژول‌ها",
    progressRatio: "۸ از ۱۲ ماژول گذرانده شده",
  },
  coaching: {
    title: "هدایت و مربیگری هوشمند (Coaching)",
    description: "پشتیبانی ساختاریافته، تاریخچه راهنمایی‌ها و تحلیل اختصاصی بدون شبیه‌سازی فریبنده انسان.",
    sourceLabel: "سیستم منتورینگ هوشمند CodeSho (شبیه‌سازی تحلیلی)",
    adviceTitle: "تحلیل عملکرد و راهنمایی تحلیلی اخیر",
    adviceText: "هیچ بن‌بستی در تعاملات اخیر شما ثبت نشده است. ساختار کدهای شما منطبق با استانداردهای کیفیت رابط کاربری و اصول تمیز است.",
    actionPrompt: "ثبت پرسش جدید از دستیار منتور",
    recommendedQuestionsTitle: "پرسش‌های پیشنهادی گام بعدی",
    q1: "چگونه ساختار State در فرم‌های چندمرحله‌ای را بهینه کنم؟",
    q2: "بهترین الگو برای تست‌های منفی دسترسی چندمستأجری چیست؟",
    q3: "روش استاندارد پیاده‌سازی تمرکز کیبورد در منوهای کشویی چیست؟",
    historyTitle: "تاریخچه بازخوردهای اخیر منتورینگ",
    h1Date: "۲ روز پیش",
    h1Content: "بررسی کامپوننت دکمه: ساختار دسترس‌پذیری عالی است، لطفاً به تضاد رنگ در حالت فوکوس دقت کنید.",
  },
  growth: {
    title: "رشد فردی و ارزیابی مهارت‌ها",
    description: "نمایش دستاوردها، اهداف یادگیری و تکامل فردی (۱۰۰٪ بدون رتبه‌بندی رقابتی، لیدربورد یا مقایسه با همسالان).",
    invariantBadge: "عدم رتبه‌بندی و مقایسه فردی فعال",
    skillsTitle: "شاخص‌های رشد و تسلط مهارتی فردی",
    skill1: "معماری کامپوننت‌های دسترس‌پذیر",
    skill1Rate: "۹۰٪ تسلط فردی",
    skill2: "پیاده‌سازی امن احراز هویت و سشن‌ها",
    skill2Rate: "۸۵٪ تسلط فردی",
    skill3: "سازگاری BiDi/RTL و جلوگیری از سرریز",
    skill3Rate: "۹۲٪ تسلط فردی",
    milestoneTitle: "نقاط عطف مهارتی پایدار",
    milestone1: "پیاده‌سازی کامل استیت‌های خطای ۴۰۳ و ۴۰۱ با هدایت دقیق کاربر",
    milestone1Date: "کسب شده در ۱۵ شهریور",
    milestone2: "ارزیابی نهایی خروجی ران‌تایم و پاس کردن ۱۰ گیت سیستمی",
    milestone2Date: "هدف پیش رو (در حال ارزیابی)",
    selfSummaryTitle: "خلاصه روند تکامل شخصی",
    selfSummaryText: "شما با استمرار روزانه توانسته‌اید نرخ تسلط خود را در ۲ هفته گذشته به میزان ۱۸٪ افزایش دهید.",
  },
  portfolio: {
    title: "پورتفولیو و نمونه‌کارهای فردی",
    description: "مجموعه پروژه‌های تکمیل‌شده در محیط آزمون و توسعه شخصی با رعایت کامل تفکیک حریم خصوصی.",
    privacyNote: "تمامی پروژه‌ها در محیط ایزوله تننت (alpha-synth) قرار دارند و هرگونه اشتراک‌گذاری عمومی مشروط به تأیید کاربر و سرپرست است.",
    project1Title: "پیاده‌سازی شل ران‌تایم فرانت‌اند و سیستم ناوبری BiDi",
    project1Status: "بررسی‌شده و معتبر",
    project1Tags: "React • TypeScript • CSS Modules",
    project2Title: "پروژه ماشین حساب ماژولار با تست‌های ایزوله",
    project2Status: "در صف بازبینی منتور",
    project2Tags: "Python • Docker • Architecture",
    actionView: "مشاهده جزئیات پروژه",
    actionAdd: "ثبت پروژه جدید در پورتفولیو",
    privacyBadge: "حریم خصوصی ایزوله (Tenant Scoped)",
  },
  states: {
    emptyTitle: "موردی برای نمایش وجود ندارد",
    emptyDesc: "هیچ داده‌ای در این بخش ثبت نشده است. می‌توانید با شروع فعالیت جدید اقدام کنید.",
    loadingTitle: "در حال دریافت اطلاعات...",
    errorTitle: "خطا در برقراری ارتباط",
    errorDesc: "پاسخ معتبری از سرور دریافت نشد. لطفاً دوباره تلاش کنید.",
    retryButton: "تلاش مجدد",
  },
} as const;
