# Generated by Django 5.2 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasscodeCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("encoded_hash", models.CharField(max_length=256)),
                ("pepper_id", models.CharField(max_length=64)),
                ("must_change", models.BooleanField(default=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("credential_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passcode_credential",
                        to="identity.user",
                    ),
                ),
            ],
        ),
    ]
