# Generated by Django 5.2.17 on 2026-08-08 16:59
# ruff: noqa: E501

import uuid

from django.db import migrations, models

RLS_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'codesho_runtime') THEN
        RAISE EXCEPTION 'codesho_runtime role must exist before cleanup claim migration';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'codesho_runtime' AND (rolsuper OR rolbypassrls)) THEN
        RAISE EXCEPTION 'codesho_runtime must not be superuser or BYPASSRLS';
    END IF;
END;
$$;
ALTER TABLE codesho.identity_cleanupworkclaim OWNER TO codesho_migrator;
ALTER TABLE codesho.identity_cleanupworkclaim ENABLE ROW LEVEL SECURITY;
ALTER TABLE codesho.identity_cleanupworkclaim FORCE ROW LEVEL SECURITY;
CREATE POLICY cleanup_claim_tenant_isolation
ON codesho.identity_cleanupworkclaim
USING (tenant_id::text = NULLIF(current_setting('app.tenant_id', true), ''))
WITH CHECK (tenant_id::text = NULLIF(current_setting('app.tenant_id', true), ''));
REVOKE ALL ON TABLE codesho.identity_cleanupworkclaim FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON TABLE codesho.identity_cleanupworkclaim TO codesho_runtime;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE codesho.identity_cleanupworkclaim FROM codesho_runtime;
"""

REVERSE_RLS_SQL = """
DROP POLICY IF EXISTS cleanup_claim_tenant_isolation ON codesho.identity_cleanupworkclaim;
ALTER TABLE codesho.identity_cleanupworkclaim DISABLE ROW LEVEL SECURITY;
"""


def install_rls(apps, schema_editor):  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(RLS_SQL)


def remove_rls(apps, schema_editor):  # type: ignore[no-untyped-def]
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVERSE_RLS_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0010_synthetic_account_bootstrap"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanupWorkClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "passcode_change_challenge_cleanup",
                                "Passcode change challenge cleanup",
                            )
                        ],
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("retryable", "Retryable"),
                            ("succeeded", "Succeeded"),
                            ("dead", "Dead"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("next_eligible_at", models.DateTimeField()),
                ("owner_token", models.UUIDField(blank=True, editable=False, null=True)),
                ("fencing_generation", models.PositiveBigIntegerField(default=0, editable=False)),
                ("claimed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("started_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("completed_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0, editable=False)),
                (
                    "last_failure_code",
                    models.CharField(blank=True, editable=False, max_length=32, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "next_eligible_at", "id"], name="cleanup_claim_due_idx"
                    ),
                    models.Index(fields=["tenant_id", "state"], name="cleanup_claim_tenant_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind", "passcode_change_challenge_cleanup")),
                        name="cleanup_claim_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fencing_generation__gte", 0)),
                        name="cleanup_claim_generation_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("retry_count__gte", 0)),
                        name="cleanup_claim_retry_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("owner_token__isnull", True),
                                ("state__in", ["pending", "retryable", "succeeded", "dead"]),
                            ),
                            models.Q(
                                ("owner_token__isnull", False),
                                ("state__in", ["claimed", "dispatched", "running"]),
                            ),
                            _connector="OR",
                        ),
                        name="cleanup_claim_ownership_consistent",
                    ),
                ],
            },
        ),
        migrations.RunPython(install_rls, reverse_code=remove_rls),
    ]
