from django.urls import path

from .views import (
    AdminLearningCurriculumView,
    AdminLearningTransitionView,
    CourseLessonListView,
    CourseListView,
    LearningPathListView,
    MentorCompleteReviewView,
    MentorMetricsView,
    MentorReviewQueueView,
    MentorStartReviewView,
    MentorSubmissionDetailView,
    ParentStudentFeedbackListView,
    ParentStudentProgressListView,
    ParentStudentSummaryView,
    RoleActivityFeedView,
    NotificationListView,
    NotificationMarkReadView,
    StudentCourseAnalyticsView,
    StudentDashboardSummaryView,
    StudentFeedbackView,
    StudentGamificationView,
    StudentEnrollmentView,
    StudentEnrollActionView,
    CohortListView,
    SubmissionDraftView,
    SubmissionSubmitView,
    SyntheticMediaAttachmentView,
    CodeAssessmentListView,
    CodePlaygroundRunView,
    CodeAssessmentSubmitView,
    AssessmentResultListView,
    StudentCertificateListView,
    StudentCertificateDetailView,
    PublicCertificateVerificationView,
    StudentAchievementTimelineView,
)

urlpatterns = [
    path("paths/", LearningPathListView.as_view(), name="learning-path-list"),
    path("courses/", CourseListView.as_view(), name="learning-course-list"),
    path(
        "courses/<str:course_id>/lessons/",
        CourseLessonListView.as_view(),
        name="learning-course-lesson-list",
    ),
    path(
        "student/dashboard/",
        StudentDashboardSummaryView.as_view(),
        name="learning-student-dashboard",
    ),
    path("submissions/draft/", SubmissionDraftView.as_view(), name="learning-submission-draft"),
    path(
        "submissions/<str:submission_id>/submit/",
        SubmissionSubmitView.as_view(),
        name="learning-submission-submit",
    ),
    path("mentor/queue/", MentorReviewQueueView.as_view(), name="learning-mentor-queue"),
    path(
        "mentor/submissions/<str:submission_id>/",
        MentorSubmissionDetailView.as_view(),
        name="learning-mentor-submission-detail",
    ),
    path(
        "mentor/submissions/<str:submission_id>/start-review/",
        MentorStartReviewView.as_view(),
        name="learning-mentor-start-review",
    ),
    path(
        "mentor/submissions/<str:submission_id>/complete-review/",
        MentorCompleteReviewView.as_view(),
        name="learning-mentor-complete-review",
    ),
    path(
        "student/submissions/<str:submission_id>/feedback/",
        StudentFeedbackView.as_view(),
        name="learning-student-submission-feedback",
    ),
    # Parent Experience Endpoints
    path(
        "parent/students/<str:student_id>/summary/",
        ParentStudentSummaryView.as_view(),
        name="learning-parent-student-summary",
    ),
    path(
        "parent/students/<str:student_id>/progress/",
        ParentStudentProgressListView.as_view(),
        name="learning-parent-student-progress",
    ),
    path(
        "parent/students/<str:student_id>/feedbacks/",
        ParentStudentFeedbackListView.as_view(),
        name="learning-parent-student-feedbacks",
    ),
    # Admin Curriculum Operations Endpoints
    path(
        "admin/curriculum/",
        AdminLearningCurriculumView.as_view(),
        name="learning-admin-curriculum",
    ),
    path(
        "admin/curriculum/transition/",
        AdminLearningTransitionView.as_view(),
        name="learning-admin-curriculum-transition",
    ),
    # Phase 3 Synthetic Media Attachment Endpoints
    path(
        "lessons/<str:lesson_id>/media/",
        SyntheticMediaAttachmentView.as_view(),
        name="learning-lesson-media",
    ),
    # Phase 3 VS2 Product Events, Projections & Activity Feeds
    path(
        "analytics/student/progress/",
        StudentCourseAnalyticsView.as_view(),
        name="learning-student-course-analytics",
    ),
    path(
        "analytics/mentor/metrics/",
        MentorMetricsView.as_view(),
        name="learning-mentor-metrics",
    ),
    path(
        "activity/feed/",
        RoleActivityFeedView.as_view(),
        name="learning-role-activity-feed",
    ),
    # Phase 3 VS3 Notifications
    path(
        "notifications/",
        NotificationListView.as_view(),
        name="learning-notification-list",
    ),
    path(
        "notifications/<str:notification_id>/read/",
        NotificationMarkReadView.as_view(),
        name="learning-notification-mark-read",
    ),
    # Phase 3 VS4 Gamification & Progression
    path(
        "student/gamification/",
        StudentGamificationView.as_view(),
        name="learning-student-gamification",
    ),
    # Phase 3 VS5 Student Course Enrollment, Cohort Capacity & Progression Policies
    path(
        "student/enrollments/",
        StudentEnrollmentView.as_view(),
        name="learning-student-enrollments",
    ),
    path(
        "student/enroll/",
        StudentEnrollActionView.as_view(),
        name="learning-student-enroll",
    ),
    path(
        "courses/<uuid:course_id>/cohorts/",
        CohortListView.as_view(),
        name="learning-course-cohorts",
    ),
    # Phase 3 VS7 Advanced Assessment, Automated Evaluation & Code Playground
    path(
        "lessons/<uuid:lesson_id>/assessments/",
        CodeAssessmentListView.as_view(),
        name="learning-lesson-assessments",
    ),
    path(
        "playground/run/",
        CodePlaygroundRunView.as_view(),
        name="learning-playground-run",
    ),
    path(
        "assessments/<uuid:assessment_id>/submit/",
        CodeAssessmentSubmitView.as_view(),
        name="learning-assessment-submit",
    ),
    path(
        "student/assessments/results/",
        AssessmentResultListView.as_view(),
        name="learning-student-assessment-results",
    ),
    # Phase 3 VS8 Course Completion Certification & Learning Verification
    path(
        "student/certificates/",
        StudentCertificateListView.as_view(),
        name="learning-student-certificates",
    ),
    path(
        "student/certificates/<uuid:certificate_id>/",
        StudentCertificateDetailView.as_view(),
        name="learning-student-certificate-detail",
    ),
    path(
        "certificates/verify/",
        PublicCertificateVerificationView.as_view(),
        name="learning-certificate-verify",
    ),
    path(
        "student/achievements/",
        StudentAchievementTimelineView.as_view(),
        name="learning-student-achievements",
    ),
]

