from django.urls import path

from . import views
from .views import (
    AdminLearningCurriculumView,
    AdminLearningTransitionView,
    CourseLessonListView,
    CourseListView,
    LearningPathListView,
    MentorCompleteReviewView,
    MentorMetricsView,
    MentorReviewQueueView,
    MentorStartReviewView,
    MentorSubmissionDetailView,
    ParentStudentFeedbackListView,
    ParentStudentProgressListView,
    ParentStudentSummaryView,
    RoleActivityFeedView,
    NotificationListView,
    NotificationMarkReadView,
    StudentCourseAnalyticsView,
    StudentDashboardSummaryView,
    StudentFeedbackView,
    StudentGamificationView,
    StudentEnrollmentView,
    StudentEnrollActionView,
    CohortListView,
    SubmissionDraftView,
    SubmissionSubmitView,
    SyntheticMediaAttachmentView,
    CodeAssessmentListView,
    CodePlaygroundRunView,
    CodeAssessmentSubmitView,
    AssessmentResultListView,
    StudentCertificateListView,
    StudentCertificateDetailView,
    PublicCertificateVerificationView,
    StudentAchievementTimelineView,
    MentorCohortAnalyticsView,
    MentorCohortAlertsView,
)

urlpatterns = [
    path("paths/", LearningPathListView.as_view(), name="learning-path-list"),
    path("courses/", CourseListView.as_view(), name="learning-course-list"),
    path(
        "courses/<str:course_id>/lessons/",
        CourseLessonListView.as_view(),
        name="learning-course-lesson-list",
    ),
    path(
        "student/dashboard/",
        StudentDashboardSummaryView.as_view(),
        name="learning-student-dashboard",
    ),
    path("submissions/draft/", SubmissionDraftView.as_view(), name="learning-submission-draft"),
    path(
        "submissions/<str:submission_id>/submit/",
        SubmissionSubmitView.as_view(),
        name="learning-submission-submit",
    ),
    path("mentor/queue/", MentorReviewQueueView.as_view(), name="learning-mentor-queue"),
    path(
        "mentor/submissions/<str:submission_id>/",
        MentorSubmissionDetailView.as_view(),
        name="learning-mentor-submission-detail",
    ),
    path(
        "mentor/submissions/<str:submission_id>/start-review/",
        MentorStartReviewView.as_view(),
        name="learning-mentor-start-review",
    ),
    path(
        "mentor/submissions/<str:submission_id>/complete-review/",
        MentorCompleteReviewView.as_view(),
        name="learning-mentor-complete-review",
    ),
    path(
        "student/submissions/<str:submission_id>/feedback/",
        StudentFeedbackView.as_view(),
        name="learning-student-submission-feedback",
    ),
    # Parent Experience Endpoints
    path(
        "parent/students/<str:student_id>/summary/",
        ParentStudentSummaryView.as_view(),
        name="learning-parent-student-summary",
    ),
    path(
        "parent/students/<str:student_id>/progress/",
        ParentStudentProgressListView.as_view(),
        name="learning-parent-student-progress",
    ),
    path(
        "parent/students/<str:student_id>/feedbacks/",
        ParentStudentFeedbackListView.as_view(),
        name="learning-parent-student-feedbacks",
    ),
    # Admin Curriculum Operations Endpoints
    path(
        "admin/curriculum/",
        AdminLearningCurriculumView.as_view(),
        name="learning-admin-curriculum",
    ),
    path(
        "admin/curriculum/transition/",
        AdminLearningTransitionView.as_view(),
        name="learning-admin-curriculum-transition",
    ),
    # Phase 3 Synthetic Media Attachment Endpoints
    path(
        "lessons/<str:lesson_id>/media/",
        SyntheticMediaAttachmentView.as_view(),
        name="learning-lesson-media",
    ),
    # Phase 3 VS2 Product Events, Projections & Activity Feeds
    path(
        "analytics/student/progress/",
        StudentCourseAnalyticsView.as_view(),
        name="learning-student-course-analytics",
    ),
    path(
        "analytics/mentor/metrics/",
        MentorMetricsView.as_view(),
        name="learning-mentor-metrics",
    ),
    path(
        "activity/feed/",
        RoleActivityFeedView.as_view(),
        name="learning-role-activity-feed",
    ),
    # Phase 3 VS3 Notifications
    path(
        "notifications/",
        NotificationListView.as_view(),
        name="learning-notification-list",
    ),
    path(
        "notifications/<str:notification_id>/read/",
        NotificationMarkReadView.as_view(),
        name="learning-notification-mark-read",
    ),
    # Phase 3 VS4 Gamification & Progression
    path(
        "student/gamification/",
        StudentGamificationView.as_view(),
        name="learning-student-gamification",
    ),
    # Phase 3 VS5 Student Course Enrollment, Cohort Capacity & Progression Policies
    path(
        "student/enrollments/",
        StudentEnrollmentView.as_view(),
        name="learning-student-enrollments",
    ),
    path(
        "student/enroll/",
        StudentEnrollActionView.as_view(),
        name="learning-student-enroll",
    ),
    path(
        "courses/<uuid:course_id>/cohorts/",
        CohortListView.as_view(),
        name="learning-course-cohorts",
    ),
    # Phase 3 VS7 Advanced Assessment, Automated Evaluation & Code Playground
    path(
        "lessons/<uuid:lesson_id>/assessments/",
        CodeAssessmentListView.as_view(),
        name="learning-lesson-assessments",
    ),
    path(
        "playground/run/",
        CodePlaygroundRunView.as_view(),
        name="learning-playground-run",
    ),
    path(
        "assessments/<uuid:assessment_id>/submit/",
        CodeAssessmentSubmitView.as_view(),
        name="learning-assessment-submit",
    ),
    path(
        "student/assessments/results/",
        AssessmentResultListView.as_view(),
        name="learning-student-assessment-results",
    ),
    # Phase 3 VS8 Course Completion Certification & Learning Verification
    path(
        "student/certificates/",
        StudentCertificateListView.as_view(),
        name="learning-student-certificates",
    ),
    path(
        "student/certificates/<uuid:certificate_id>/",
        StudentCertificateDetailView.as_view(),
        name="learning-student-certificate-detail",
    ),
    path(
        "certificates/verify/",
        PublicCertificateVerificationView.as_view(),
        name="learning-certificate-verify",
    ),
    path(
        "student/achievements/",
        StudentAchievementTimelineView.as_view(),
        name="learning-student-achievements",
    ),
    # Phase 3 VS9 Enterprise Analytics Supervision & Cohort Orchestration
    path(
        "mentor/cohorts/<uuid:cohort_id>/analytics/",
        MentorCohortAnalyticsView.as_view(),
        name="learning-mentor-cohort-analytics",
    ),
    path(
        "mentor/cohorts/<uuid:cohort_id>/alerts/",
        MentorCohortAlertsView.as_view(),
        name="learning-mentor-cohort-alerts",
    ),
    path(
        "mentor/cohorts/<uuid:cohort_id>/alerts/<uuid:alert_id>/transition/",
        MentorCohortAlertsView.as_view(),
        name="learning-mentor-cohort-alert-transition",
    ),
    # Phase 3 VS10 Learning Community Discussion & Peer Interaction
    path(
        "discussions/threads/",
        views.DiscussionThreadListCreateView.as_view(),
        name="learning-discussion-threads",
    ),
    path(
        "discussions/threads/<uuid:thread_id>/",
        views.DiscussionThreadDetailView.as_view(),
        name="learning-discussion-thread-detail",
    ),
    path(
        "discussions/threads/<uuid:thread_id>/comments/",
        views.DiscussionCommentCreateView.as_view(),
        name="learning-discussion-comment-create",
    ),
    path(
        "discussions/threads/<uuid:thread_id>/pin/",
        views.DiscussionThreadPinView.as_view(),
        name="learning-discussion-thread-pin",
    ),
    path(
        "discussions/comments/<uuid:comment_id>/endorse/",
        views.DiscussionCommentEndorseView.as_view(),
        name="learning-discussion-comment-endorse",
    ),
    path(
        "discussions/moderation/action/",
        views.DiscussionModerationActionView.as_view(),
        name="learning-discussion-moderation-action",
    ),
    # Phase 3 VS11 Learning Personalization & Adaptive Progression
    path(
        "personalization/profile/",
        views.StudentProfileView.as_view(),
        name="learning-personalization-profile",
    ),
    path(
        "personalization/recommendations/",
        views.RecommendationListView.as_view(),
        name="learning-personalization-recommendations",
    ),
    path(
        "personalization/recommendations/<uuid:recommendation_id>/action/",
        views.RecommendationActionView.as_view(),
        name="learning-personalization-recommendation-action",
    ),
    path(
        "personalization/skills/",
        views.SkillGraphView.as_view(),
        name="learning-personalization-skills",
    ),
    # Phase 3 VS12 Learning Portfolio & Journey Narrative
    path(
        "portfolio/",
        views.StudentPortfolioView.as_view(),
        name="learning-portfolio-root",
    ),
    path(
        "portfolio/guardian/<uuid:student_id>/",
        views.ParentPortfolioView.as_view(),
        name="learning-portfolio-guardian",
    ),
    path(
        "portfolio/<uuid:portfolio_id>/artifacts/",
        views.AchievementArtifactView.as_view(),
        name="learning-portfolio-artifacts",
    ),
    path(
        "portfolio/journey/<uuid:student_id>/",
        views.JourneyTimelineView.as_view(),
        name="learning-portfolio-journey",
    ),
    # Phase 3 VS13 Student Growth Insights & Longitudinal Learning Intelligence
    path(
        "insights/<uuid:student_id>/",
        views.StudentGrowthInsightFeedView.as_view(),
        name="learning-growth-insights-feed",
    ),
    path(
        "insights/trends/<uuid:student_id>/",
        views.StudentGrowthTrendsView.as_view(),
        name="learning-growth-trends",
    ),
    path(
        "insights/milestones/<uuid:student_id>/",
        views.StudentMilestoneTimelineView.as_view(),
        name="learning-growth-milestones",
    ),
    path(
        "insights/recalculate/",
        views.InsightRecalculationView.as_view(),
        name="learning-insights-recalculate",
    ),
    path(
        "insights/milestones/<uuid:milestone_id>/retract/",
        views.MilestoneRetractionView.as_view(),
        name="learning-milestone-retract",
    ),
    # Phase 3 VS14 Student Learning Operations, Reflection & AI-Assisted Growth
    path(
        "reflections/",
        views.LearningReflectionListCreateView.as_view(),
        name="learning-reflections-list-create",
    ),
    path(
        "reflections/<uuid:reflection_id>/retract/",
        views.LearningReflectionRetractView.as_view(),
        name="learning-reflection-retract",
    ),
    path(
        "reflections/<uuid:reflection_id>/feedback/",
        views.MentorReflectionFeedbackCreateView.as_view(),
        name="learning-reflection-feedback",
    ),
    path(
        "goals/",
        views.StudentLearningGoalListCreateView.as_view(),
        name="learning-goals-list-create",
    ),
    path(
        "goals/<uuid:goal_id>/transition/",
        views.StudentLearningGoalTransitionView.as_view(),
        name="learning-goal-transition",
    ),
    path(
        "goals/<uuid:goal_id>/action-steps/",
        views.GoalActionPlanCreateView.as_view(),
        name="learning-goal-action-steps",
    ),
    path(
        "suggestions/",
        views.AIAssistedGrowthSuggestionView.as_view(),
        name="learning-suggestions-list",
    ),
    path(
        "suggestions/generate/",
        views.AIAssistedGrowthSuggestionView.as_view(),
        name="learning-suggestions-generate",
    ),
    # Phase 3 VS15 Learning Continuity and Student Success Planning
    path(
        "success-plans/",
        views.StudentSuccessPlanListCreateView.as_view(),
        name="learning-success-plans-list-create",
    ),
    path(
        "success-plans/<uuid:plan_id>/",
        views.StudentSuccessPlanDetailTransitionView.as_view(),
        name="learning-success-plan-detail",
    ),
    path(
        "success-plans/<uuid:plan_id>/transition/",
        views.StudentSuccessPlanDetailTransitionView.as_view(),
        name="learning-success-plan-transition",
    ),
    path(
        "success-plans/<uuid:plan_id>/steps/",
        views.SuccessActionStepCreateTransitionView.as_view(),
        name="learning-success-plan-steps",
    ),
    path(
        "success-steps/<uuid:step_id>/transition/",
        views.SuccessActionStepCreateTransitionView.as_view(),
        name="learning-success-step-transition",
    ),
    path(
        "success-plans/<uuid:plan_id>/timeline/",
        views.SuccessTimelineEventAppendView.as_view(),
        name="learning-success-plan-timeline",
    ),
]
