"use client";

import { FormEvent, useRef, useState } from "react";
import { completePasscodeChange, normalizePasscode } from "@/features/auth/authClient";
import styles from "../login/login.module.css";

const messages = { brand: "Codesho", title: "تغییر رمز ورود", label: "رمز جدید ۶ رقمی", confirm: "تکرار رمز جدید", submit: "تغییر رمز", invalid: "رمز باید دقیقاً ۶ رقم باشد.", mismatch: "رمز و تکرار آن مطابقت ندارند.", success: "رمز تغییر کرد؛ لطفاً دوباره وارد شوید.", expired: "درخواست منقضی شده است؛ دوباره وارد شوید.", same: "رمز جدید نمی‌تواند همان رمز قبلی باشد.", rate: "تعداد تلاش‌ها زیاد است؛ بعداً دوباره امتحان کنید.", unavailable: "سرویس موقتاً در دسترس نیست." };

export default function PasscodeChangePage() {
  const [passcode, setPasscode] = useState(""); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const messageRef = useRef<HTMLDivElement>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const normalized = normalizePasscode(passcode); const repeated = normalizePasscode(confirmation); if (!/^\d{6}$/.test(normalized) || !/^\d{6}$/.test(repeated)) return setMessage(messages.invalid); if (normalized !== repeated) return setMessage(messages.mismatch); setBusy(true); const result = await completePasscodeChange(normalized); setBusy(false); const text = result === "success" ? messages.success : result === "expired" ? messages.expired : result === "same_as_current" ? messages.same : result === "rate_limited" ? messages.rate : result === "unavailable" ? messages.unavailable : messages.invalid; setMessage(text); messageRef.current?.focus(); if (result === "success" || result === "expired") { setPasscode(""); setConfirmation(""); window.setTimeout(() => window.location.assign("/login"), 0); } }
  return <main className={styles.page}><section className={styles.card} aria-labelledby="change-title"><p className={styles.brand}>{messages.brand}</p><h1 id="change-title">{messages.title}</h1><form onSubmit={submit} noValidate><label className={styles.field} htmlFor="new-passcode"><span>{messages.label}</span><input id="new-passcode" type="password" inputMode="numeric" autoComplete="new-password" maxLength={6} value={passcode} onChange={(event) => setPasscode(normalizePasscode(event.target.value))} /></label><label className={styles.field} htmlFor="repeat-passcode"><span>{messages.confirm}</span><input id="repeat-passcode" type="password" inputMode="numeric" autoComplete="new-password" maxLength={6} value={confirmation} onChange={(event) => setConfirmation(normalizePasscode(event.target.value))} /></label><div className={styles.message} aria-live="polite" tabIndex={-1} ref={messageRef}>{message}</div><button className={styles.submit} type="submit" disabled={busy}>{messages.submit}</button></form></section></main>;
}
