# Generated by Django 5.2.17 on 2026-09-20 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_tenant', '0003_synthetic_membership_activation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_code', models.CharField(db_index=True, max_length=32)),
                ('display_name', models.CharField(max_length=120)),
                ('avatar_key', models.CharField(default='default', max_length=64)),
                ('level_title', models.CharField(max_length=120)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_learners', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarded_learners', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_tenant.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLearningProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_slug', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('repo_branch', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(max_length=40)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('current_milestone', models.TextField()),
                ('recent_activity', models.TextField()),
                ('last_code_snippet', models.TextField(blank=True)),
                ('skills_demonstrated', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_tenant.tenant')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='learning_loop.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MentorIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('FOLLOW_UP', 'Follow Up'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=20)),
                ('reason', models.TextField()),
                ('recommended_action', models.TextField()),
                ('mentor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_interventions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='learning_loop.activelearningproject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('MENTOR', 'Mentor'), ('STUDENT', 'Student')], max_length=16)),
                ('action_type', models.CharField(max_length=64)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_tenant.tenant')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='learning_loop.mentorintervention')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentBridge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_briefing', models.TextField()),
                ('briefing_updated_at', models.DateTimeField(auto_now=True)),
                ('parent_encouragement_sent', models.BooleanField(default=False)),
                ('parent_encouragement_message', models.TextField(blank=True)),
                ('encouragement_updated_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_bridge', to='learning_loop.learnerprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform_tenant.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='learnerprofile',
            index=models.Index(fields=['tenant', 'student_code'], name='learning_lo_tenant__4fa3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerprofile',
            index=models.Index(fields=['tenant', 'assigned_mentor'], name='learning_lo_tenant__80dd37_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerprofile',
            index=models.Index(fields=['tenant', 'guardian'], name='learning_lo_tenant__11d13d_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_learner_profile'),
        ),
        migrations.AddConstraint(
            model_name='learnerprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'student_code'), name='unique_tenant_student_code'),
        ),
        migrations.AddIndex(
            model_name='activelearningproject',
            index=models.Index(fields=['tenant', 'learner', 'is_active'], name='learning_lo_tenant__d7e04e_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorintervention',
            index=models.Index(fields=['tenant', 'status'], name='learning_lo_tenant__cdb895_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorintervention',
            index=models.Index(fields=['tenant', 'project'], name='learning_lo_tenant__5cd11c_idx'),
        ),
        migrations.AddIndex(
            model_name='interventionfeedback',
            index=models.Index(fields=['tenant', 'intervention', 'created_at'], name='learning_lo_tenant__1d5a34_idx'),
        ),
        migrations.AddIndex(
            model_name='parentbridge',
            index=models.Index(fields=['tenant', 'learner'], name='learning_lo_tenant__0aaf1c_idx'),
        ),
    ]
