# Generated by Django 5.2.16 on 2026-07-15 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('topic', models.CharField(max_length=160)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published_at', 'available_at'], name='platform_ev_publish_e96e3f_idx')],
            },
        ),
    ]
