"use client";
import { useEffect, useState } from "react";
import { getSession } from "@/features/auth/authClient";
import { fetchCourses, fetchLessons, LearningRequestError } from "@/features/dashboard/learningClient";
import type { CourseItem, LessonItem } from "@/features/dashboard/dashboard.types";
import { LearningScreen } from "./LearningScreen";
import type { LearningModel, LearningViewState } from "./learning.types";
interface Boundary { readonly state: LearningViewState; readonly model: LearningModel | null; }
const initial: Boundary = { state: "loading", model: null };
function classify(error: unknown): LearningViewState { if (!(error instanceof LearningRequestError)) return "error"; if (error.kind === "recoverable") return "recoverable-error"; return error.kind; }
export function LearningDataBoundary() { const [view, setView] = useState<Boundary>(initial); const [selectedCourseId, setSelectedCourseId] = useState<string | null>(null); useEffect(() => { const controller = new AbortController(); let mounted = true; void (async () => { try { const session = await getSession(); if (!mounted) return; if (!session) { setView({ state: "unauthenticated", model: null }); return; } const courses = await fetchCourses({ signal: controller.signal }); if (!mounted) return; if (courses.length === 0) { setView({ state: "empty", model: { displayName: session.user.username, courses, lessons: [], selectedCourseId: null } }); return; } const first = courses[0].id; setSelectedCourseId(first); setView({ state: "loading", model: { displayName: session.user.username, courses, lessons: [], selectedCourseId: first } }); } catch (error) { if (mounted && !(error instanceof DOMException && error.name === "AbortError")) setView({ state: classify(error), model: null }); } })(); return () => { mounted = false; controller.abort(); }; }, []); useEffect(() => { if (!selectedCourseId || !view.model) return; const controller = new AbortController(); let current = true; const courseId = selectedCourseId; void fetchLessons(courseId, { signal: controller.signal }).then((lessons: readonly LessonItem[]) => { if (!current) return; setView((previous) => previous.model ? { state: lessons.length ? "ready" : "lessons-empty", model: { ...previous.model, lessons, selectedCourseId: courseId } } : previous); }).catch((error: unknown) => { if (current && !(error instanceof DOMException && error.name === "AbortError")) setView({ state: classify(error), model: null }); }); return () => { current = false; controller.abort(); }; }, [selectedCourseId, view.model?.courses.length]); const selectCourse = (courseId: string) => { if (!view.model || !view.model.courses.some((course: CourseItem) => course.id === courseId)) return; setSelectedCourseId(courseId); setView({ state: "loading", model: { ...view.model, lessons: [], selectedCourseId: courseId } }); }; return <LearningScreen state={view.state} model={view.model ?? undefined} onSelectCourse={selectCourse} />; }
